/**
 * Which bearer opens which trigger, established rather than assumed.
 *
 * The defect this answers is a *reading* rather than a bug: four Routines
 * registered against four deployment secrets in the order somebody wrote them
 * down, four provider `AUTH 401`s, and the conclusion that four bearers must be
 * regenerated by a person. Four refusals close four of sixteen cells. The
 * fleet was one relabelling away from working.
 *
 * So most of this file is about what the search may *not* do: re-test a cell,
 * widen past the square, close a cell on a rate limit, or let a secret value
 * reach a row. A search that eliminated a true pairing on a bad minute would
 * burn it out of the space permanently, which is worse than never having run.
 */
import { afterEach, beforeEach, describe, expect, it } from 'vitest';
import { freshProject } from './helpers.ts';
import { listIdentityEvents } from '../server/repos/identity.ts';
import {
  createAccount,
  createRoutine,
  getRoutine,
  listRoutines,
  setRoutineSecret,
  setRoutineState,
} from '../server/repos/fleet.ts';
import {
  decidedPairs,
  digestOfSecret,
  planPairs,
  recordPairAttempt,
  seedFromRows,
  stopsTrigger,
  tryPair,
  type DecidedPair,
} from '../server/services/dispatch/secretReconcile.ts';
import type { FleetRoutine } from '../server/domain/types.ts';

const realFetch = globalThis.fetch;

/** The true mapping the provider enforces: trigger ref -> the one bearer that opens it. */
let truth: Record<string, string> = {};
/** Refs the provider answers with a rate limit rather than a verdict. */
let rateLimited = new Set<string>();
let fires: { ref: string; bearer: string }[] = [];

const SECRETS = ['RECON_TEST_A', 'RECON_TEST_B', 'RECON_TEST_C'] as const;

async function fleetOfThree(): Promise<FleetRoutine[]> {
  const account = await createAccount({ provider: 'anthropic', name: 'recon-account' });
  for (const [ref, name, secret] of [
    ['trig_one', 'R-one', 'RECON_TEST_A'],
    ['trig_two', 'R-two', 'RECON_TEST_B'],
    ['trig_three', 'R-three', 'RECON_TEST_C'],
  ] as const) {
    await createRoutine({ accountId: account.id, routineRef: ref, name, tokenSecretName: secret });
  }
  return (await listRoutines()).filter((one) => one.accountId === account.id);
}

beforeEach(async () => {
  await freshProject();
  fires = [];
  rateLimited = new Set();
  // Deliberately scrambled: every diagonal pairing is wrong, which is the
  // production shape. A -> two, B -> three, C -> one.
  truth = { trig_two: 'value-A', trig_three: 'value-B', trig_one: 'value-C' };
  process.env['RECON_TEST_A'] = 'value-A';
  process.env['RECON_TEST_B'] = 'value-B';
  process.env['RECON_TEST_C'] = 'value-C';

  globalThis.fetch = (async (input: RequestInfo | URL, init?: RequestInit) => {
    const url = String(input);
    const ref = url.match(/routines\/([^/]+)\/fire/)?.[1] ?? '';
    const header = String((init?.headers as Record<string, string> | undefined)?.['Authorization'] ?? '');
    const bearer = header.replace(/^Bearer /, '');
    fires.push({ ref, bearer });
    if (rateLimited.has(ref)) {
      return new Response(JSON.stringify({ error: { message: 'slow down' } }), {
        status: 429,
        headers: { 'Retry-After': '1' },
      });
    }
    if (truth[ref] === bearer) {
      return new Response(JSON.stringify({ claude_code_session_id: `cse_${ref}` }), { status: 200 });
    }
    return new Response(
      JSON.stringify({
        error: { message: 'Token is not authorized for this routine', type: 'authentication_error' },
      }),
      { status: 401 },
    );
  }) as typeof globalThis.fetch;
});

afterEach(() => {
  globalThis.fetch = realFetch;
  for (const name of SECRETS) delete process.env[name];
});

/** Walk the square the way `reconcile-secrets` does, and count what it spent. */
async function walk(routines: FleetRoutine[]): Promise<{ matched: string[]; spent: number }> {
  const decided: DecidedPair[] = await decidedPairs(routines.map((one) => one.id));
  const plan = planPairs(routines, decided);
  const lockedRoutines = new Set(plan.locked.map((one) => one.routineId));
  const lockedSecrets = new Set(plan.locked.map((one) => one.secretName));
  const stopped = new Set<string>();
  const matched: string[] = [];
  let spent = 0;
  for (const pair of plan.pairs) {
    if (lockedRoutines.has(pair.routineId) || lockedSecrets.has(pair.secretName)) continue;
    if (stopped.has(pair.routineId)) continue;
    const routine = routines.find((one) => one.id === pair.routineId)!;
    spent += 1;
    const verdict = await tryPair(pair, routine);
    await recordPairAttempt(verdict, 'test');
    if (verdict.outcome === 'MATCHED') {
      matched.push(`${pair.routineRef}<-${pair.secretName}`);
      lockedRoutines.add(pair.routineId);
      lockedSecrets.add(pair.secretName);
      const digest = digestOfSecret(pair.secretName);
      if (digest) {
        await setRoutineSecret({
          routineId: routine.id,
          tokenSecretName: pair.secretName,
          tokenDigest: digest,
          actor: 'test',
          reason: 'matched',
        });
      }
    } else if (stopsTrigger(verdict)) {
      stopped.add(pair.routineId);
    }
  }
  return { matched, spent };
}

describe('the square, and what bounds it', () => {
  it('never offers a cell twice, and locks a match out on both axes', async () => {
    const routines = await fleetOfThree();
    const first = planPairs(routines, []);
    expect(first.cells).toBe(9);
    expect(first.pairs).toHaveLength(9);

    const afterMatch = planPairs(routines, [
      { routineId: routines[0]!.id, secretName: 'RECON_TEST_B', outcome: 'MATCHED' },
    ]);
    // That trigger is answered, and that secret cannot be the answer anywhere else.
    expect(afterMatch.pairs.some((pair) => pair.routineId === routines[0]!.id)).toBe(false);
    expect(afterMatch.pairs.some((pair) => pair.secretName === 'RECON_TEST_B')).toBe(false);
    expect(afterMatch.pairs).toHaveLength(4);
  });

  it('skips an eliminated cell without touching its neighbours', async () => {
    const routines = await fleetOfThree();
    const plan = planPairs(routines, [
      { routineId: routines[0]!.id, secretName: 'RECON_TEST_A', outcome: 'ELIMINATED' },
    ]);
    expect(plan.pairs).toHaveLength(8);
    expect(
      plan.pairs.some(
        (pair) => pair.routineId === routines[0]!.id && pair.secretName === 'RECON_TEST_A',
      ),
    ).toBe(false);
    // The rest of that trigger's row is still open: one refusal is one cell.
    expect(plan.pairs.filter((pair) => pair.routineId === routines[0]!.id)).toHaveLength(2);
  });

  it('is deterministic, so "why was this tried" is answerable afterwards', async () => {
    const routines = await fleetOfThree();
    const a = planPairs(routines, []).pairs.map((pair) => `${pair.routineRef}/${pair.secretName}`);
    const b = planPairs([...routines].reverse(), []).pairs.map(
      (pair) => `${pair.routineRef}/${pair.secretName}`,
    );
    expect(a).toEqual(b);
  });
});

describe('what the existing rows already answer', () => {
  it('reads a quarantined AUTH refusal as one closed cell', async () => {
    const routines = await fleetOfThree();
    await setRoutineState({
      routineId: routines[0]!.id,
      from: 'ENABLED',
      to: 'QUARANTINED',
      reason: 'The provider refused a fire with AUTH: 401 {"error":{"message":"Token is not authorized"}}',
    });
    const seeded = seedFromRows((await listRoutines()).filter((one) => one.accountId === routines[0]!.accountId));
    expect(seeded).toHaveLength(1);
    expect(seeded[0]).toMatchObject({ routineId: routines[0]!.id, outcome: 'ELIMINATED' });
    expect(seeded[0]!.secretName).toBe(routines[0]!.tokenSecretName);
  });

  it('infers nothing from a quarantine that is not about a token', async () => {
    const routines = await fleetOfThree();
    await setRoutineState({
      routineId: routines[0]!.id,
      from: 'ENABLED',
      to: 'QUARANTINED',
      reason: 'sessions complete without checking in operator hold',
    });
    await setRoutineState({
      routineId: routines[1]!.id,
      from: 'ENABLED',
      to: 'QUARANTINED',
      reason: 'The provider refused a fire with NOT_FOUND: 404',
    });
    const seeded = seedFromRows((await listRoutines()).filter((one) => one.accountId === routines[0]!.accountId));
    expect(seeded).toHaveLength(0);
  });

  it('infers nothing from a healthy surface', async () => {
    const routines = await fleetOfThree();
    expect(seedFromRows(routines)).toHaveLength(0);
  });
});

describe('asking the provider about one cell', () => {
  it('reads a 401 as this cell and not as this bearer', async () => {
    const routines = await fleetOfThree();
    const routine = routines.find((one) => one.routineRef === 'trig_one')!;
    const verdict = await tryPair(
      { routineId: routine.id, routineRef: 'trig_one', routineName: routine.name, secretName: 'RECON_TEST_A' },
      routine,
    );
    expect(verdict.outcome).toBe('ELIMINATED');
    expect(verdict.kind).toBe('AUTH');
    // The same bearer opens a different door, which is the whole point.
    const other = routines.find((one) => one.routineRef === 'trig_two')!;
    const second = await tryPair(
      { routineId: other.id, routineRef: 'trig_two', routineName: other.name, secretName: 'RECON_TEST_A' },
      other,
    );
    expect(second.outcome).toBe('MATCHED');
  });

  it('records a rate limit as nothing learned, and closes no cell', async () => {
    const routines = await fleetOfThree();
    const routine = routines.find((one) => one.routineRef === 'trig_one')!;
    rateLimited.add('trig_one');
    const verdict = await tryPair(
      { routineId: routine.id, routineRef: 'trig_one', routineName: routine.name, secretName: 'RECON_TEST_C' },
      routine,
    );
    expect(verdict.outcome).toBe('INCONCLUSIVE');
    expect(stopsTrigger(verdict)).toBe(true);
    await recordPairAttempt(verdict, 'test');
    // The cell that would have matched is still open.
    const plan = planPairs(routines, await decidedPairs(routines.map((one) => one.id)));
    expect(
      plan.pairs.some((pair) => pair.routineId === routine.id && pair.secretName === 'RECON_TEST_C'),
    ).toBe(true);
  });

  it('says a named variable is absent rather than firing at nothing', async () => {
    const routines = await fleetOfThree();
    const routine = routines[0]!;
    delete process.env['RECON_TEST_A'];
    const before = fires.length;
    const verdict = await tryPair(
      { routineId: routine.id, routineRef: routine.routineRef, routineName: routine.name, secretName: 'RECON_TEST_A' },
      routine,
    );
    expect(verdict.outcome).toBe('SECRET_ABSENT');
    expect(fires.length).toBe(before);
  });
});

describe('the whole reconciliation', () => {
  it('finds a fully scrambled mapping inside the square, and locks as it goes', async () => {
    const routines = await fleetOfThree();
    const { matched, spent } = await walk(routines);
    expect(matched.sort()).toEqual(
      ['trig_one<-RECON_TEST_C', 'trig_three<-RECON_TEST_B', 'trig_two<-RECON_TEST_A'].sort(),
    );
    // Bounded by the square, and in practice well inside it.
    expect(spent).toBeLessThanOrEqual(9);
    // Every fire was a cell in this square: no widening, no repeats.
    const seen = new Set(fires.map((fire) => `${fire.ref}/${fire.bearer}`));
    expect(seen.size).toBe(fires.length);
  });

  it('repoints the rows it proved, and only those', async () => {
    const routines = await fleetOfThree();
    await walk(routines);
    const after = await listRoutines();
    const byRef = new Map(after.map((one) => [one.routineRef, one]));
    expect(byRef.get('trig_one')!.tokenSecretName).toBe('RECON_TEST_C');
    expect(byRef.get('trig_two')!.tokenSecretName).toBe('RECON_TEST_A');
    expect(byRef.get('trig_three')!.tokenSecretName).toBe('RECON_TEST_B');
  });

  it('costs nothing to run again, because a decided cell is durable', async () => {
    const routines = await fleetOfThree();
    await walk(routines);
    const spentFirst = fires.length;
    const again = await walk(await listRoutines().then((all) => all.filter((one) => one.accountId === routines[0]!.accountId)));
    expect(again.spent).toBe(0);
    expect(fires.length).toBe(spentFirst);
  });

  it('leaves every surface exactly as healthy as it found it', async () => {
    const routines = await fleetOfThree();
    for (const routine of routines) {
      await setRoutineState({
        routineId: routine.id,
        from: 'ENABLED',
        to: 'QUARANTINED',
        reason: 'The provider refused a fire with AUTH: 401',
      });
    }
    const live = (await listRoutines()).filter((one) => one.accountId === routines[0]!.accountId);
    await walk(live);
    for (const routine of live) {
      // Re-enabling is `fleet set-state`, and a diagnostic that lifted its own
      // quarantine would be grading its own exam.
      expect((await getRoutine(routine.id))!.state).toBe('QUARANTINED');
    }
  });
});

describe('what may never reach a row', () => {
  it('audits a repoint by name and digest prefix, never by value', async () => {
    const routines = await fleetOfThree();
    const routine = routines[0]!;
    const digest = digestOfSecret('RECON_TEST_B')!;
    const after = await setRoutineSecret({
      routineId: routine.id,
      tokenSecretName: 'RECON_TEST_B',
      tokenDigest: digest,
      actor: 'test',
      reason: 'reconciled',
    });
    expect(after!.tokenSecretName).toBe('RECON_TEST_B');
    const events = await listIdentityEvents({ action: 'SET_ROUTINE_SECRET', limit: 10 });
    expect(events).toHaveLength(1);
    const blob = JSON.stringify(events[0]!.metadata);
    expect(blob).toContain('RECON_TEST_B');
    expect(blob).not.toContain('value-B');
    expect(blob).not.toContain(digest); // the prefix, never the whole digest
  });

  it('writes no secret value into any attempt it records', async () => {
    const routines = await fleetOfThree();
    await walk(routines);
    const events = await listIdentityEvents({ action: 'RECONCILE_ROUTINE_SECRET', limit: 100 });
    expect(events.length).toBeGreaterThan(0);
    const blob = JSON.stringify(events.map((event) => event.metadata));
    for (const value of ['value-A', 'value-B', 'value-C']) expect(blob).not.toContain(value);
  });

  it('refuses a repoint of a Routine that is not there', async () => {
    expect(
      await setRoutineSecret({
        routineId: 'rtn_nope',
        tokenSecretName: 'RECON_TEST_A',
        tokenDigest: 'x',
        actor: 'test',
        reason: 'r',
      }),
    ).toBeNull();
  });
});
