/**
 * Which trigger a bearer actually authorizes, established by elimination.
 *
 * ---------------------------------------------------------------------------
 * The reading this exists to correct
 * ---------------------------------------------------------------------------
 *
 * A provider `AUTH 401` on a fire says one thing, and it is narrower than it
 * looks: **this token does not authorize this trigger.** It does not say the
 * token is invalid, revoked, expired, or from another account. Four Routines
 * registered against four deployment secrets, paired in the order somebody
 * happened to write them down, produce four refusals — and those four refusals
 * eliminate four of sixteen pairings and say nothing at all about the other
 * twelve.
 *
 * That is exactly the state this Brain reached. Every `fleet show` row read
 * `QUARANTINED` with the provider's own words on it, every reading was correct,
 * and the conclusion drawn from them — *these bearers must be regenerated by a
 * person* — did not follow. A fleet can be one relabelling away from working
 * while looking permanently broken, and the only way to tell is to ask.
 *
 * ---------------------------------------------------------------------------
 * What makes it bounded rather than a retry storm
 * ---------------------------------------------------------------------------
 *
 * The search space is a square: n triggers against the n secret names those
 * same triggers are registered with. It is never widened — a secret belonging
 * to another account is not a candidate, because the question is which of
 * *these* bearers opens which of *these* doors.
 *
 * Every cell is visited at most once, ever. A decided cell is persisted, so a
 * second run costs nothing and a crashed run resumes rather than restarting.
 * A match **locks**: its trigger and its secret both leave the space, which is
 * what makes this a one-to-one reconciliation and not n² probing — four
 * triggers cost at most 4 + 3 + 2 + 1 = 10 further fires, and in practice
 * fewer.
 *
 * And a failure that is not about the pairing never eliminates anything. A rate
 * limit, a 5xx and a dead connection are conditions of the moment; recording
 * one as "this bearer does not open this door" would burn a true pairing out of
 * the space permanently on a bad minute. They stop the run for that trigger and
 * are reported as inconclusive, which is §30's rule at a new table: *we could
 * not tell* must never read the same as *we checked*.
 *
 * ---------------------------------------------------------------------------
 * What it costs, said rather than glossed
 * ---------------------------------------------------------------------------
 *
 * A fire that succeeds **starts a real Claude session**, and Brain sends no
 * text with it (see `fire.ts`), so that session authenticates, checks in, and
 * is handed whatever its worker is entitled to — or nothing. There is no way to
 * ask the provider "would this token work" without using it, so the cost of
 * proving a pairing is one activation on the account that owns it. At most one
 * per trigger, and only on the pairing that is correct.
 *
 * Pinning a probe bin at it first would be worse rather than better: a pinned
 * bin is answerable only by the session Brain's own dispatcher fired at that
 * Routine (§27), and this fire is deliberately outside the dispatcher, so the
 * bin would be refused by the very guard that makes pinning meaningful. The
 * honest order is: reconcile the mapping here, then re-enable the surface, then
 * prove it with `verify-surface --probe` through the dispatcher, which is the
 * four-row chain that actually establishes a surface works.
 *
 * ---------------------------------------------------------------------------
 * What it never does
 * ---------------------------------------------------------------------------
 *
 * It reads no secret value into anything but the one `Authorization` header
 * `fireRoutine` builds, prints none, stores none, and moves no deployment
 * variable. It re-enables nothing: a quarantine is a health state a person
 * answers with `fleet set-state`, and a diagnostic that lifted one because it
 * liked its own result would be the evaluator grading its own exam.
 */
import { credentialDigest } from '../../repos/fleet.ts';
import { listIdentityEvents, recordIdentityEvent } from '../../repos/identity.ts';
import { fireRoutine, resolveToken, type FireErrorKind } from './fire.ts';
import type { FleetRoutine } from '../../domain/types.ts';

/** What one visit to one cell established. */
export type PairOutcome =
  /** The provider refused this bearer for this trigger. The cell is closed. */
  | 'ELIMINATED'
  /** The provider accepted it. The trigger and the secret both leave the space. */
  | 'MATCHED'
  /** Nothing about the pairing was learned. The cell stays open. */
  | 'INCONCLUSIVE'
  /** The deployment has no variable of that name. Nothing to test with. */
  | 'SECRET_ABSENT';

export interface Pair {
  routineId: string;
  routineRef: string;
  routineName: string;
  secretName: string;
}

export interface PairVerdict extends Pair {
  outcome: PairOutcome;
  /** The provider's category, where there was one. */
  kind: FireErrorKind | null;
  detail: string;
}

/** A cell whose answer is already known, however it became known. */
export interface DecidedPair {
  routineId: string;
  secretName: string;
  outcome: PairOutcome;
}

const ACTION = 'RECONCILE_ROUTINE_SECRET';

/**
 * The cells the existing rows already answer.
 *
 * A quarantined Routine carrying a recorded `AUTH` refusal was refused *while
 * registered against the secret its row currently names*, so that one cell is
 * closed and the evidence for it is the row itself. This is read once, before
 * anything is repointed — afterwards the row names a different secret and its
 * reason is about a pairing that no longer exists, which is why every seeded
 * elimination is written into the durable log on the first pass rather than
 * re-derived on the next one.
 *
 * Nothing else is inferred. A Routine quarantined for any other reason, or
 * carrying no reason at all, contributes no elimination: not knowing is an
 * answer, and a guess here costs a true pairing.
 */
export function seedFromRows(routines: FleetRoutine[]): DecidedPair[] {
  const seeded: DecidedPair[] = [];
  for (const routine of routines) {
    const reason = routine.stateReason ?? '';
    if (routine.state !== 'QUARANTINED') continue;
    if (!/\bAUTH\b/.test(reason)) continue;
    seeded.push({
      routineId: routine.id,
      secretName: routine.tokenSecretName,
      outcome: 'ELIMINATED',
    });
  }
  return seeded;
}

function key(routineId: string, secretName: string): string {
  return `${routineId}\u0000${secretName}`;
}

export interface Plan {
  /** Every cell still worth visiting, in a deterministic order. */
  pairs: Pair[];
  /** Triggers whose secret is already established. */
  locked: { routineId: string; secretName: string }[];
  /** The square this search is bounded by. */
  cells: number;
  /** Cells already decided, counted against `cells`. */
  decided: number;
}

/**
 * The remaining search, as a decision over rows and nothing else.
 *
 * Pure, and kept that way for `router.ts`'s reason: "why was this pairing
 * tried" has to be answerable afterwards from a recorded input rather than
 * from a re-run against a fleet that has moved. Being pure also makes it
 * useless as a safety mechanism, which is why the *bound* is re-asserted by the
 * caller against the same square rather than trusted from here.
 */
export function planPairs(routines: FleetRoutine[], decided: DecidedPair[]): Plan {
  const secretNames = [...new Set(routines.map((routine) => routine.tokenSecretName))].sort();
  const ordered = [...routines].sort((a, b) => a.routineRef.localeCompare(b.routineRef));

  const matched = decided.filter((one) => one.outcome === 'MATCHED');
  const lockedRoutines = new Set(matched.map((one) => one.routineId));
  const lockedSecrets = new Set(matched.map((one) => one.secretName));
  const closed = new Set(
    decided
      .filter((one) => one.outcome === 'ELIMINATED' || one.outcome === 'MATCHED')
      .map((one) => key(one.routineId, one.secretName)),
  );

  const pairs: Pair[] = [];
  for (const routine of ordered) {
    if (lockedRoutines.has(routine.id)) continue;
    for (const secretName of secretNames) {
      if (lockedSecrets.has(secretName)) continue;
      if (closed.has(key(routine.id, secretName))) continue;
      pairs.push({
        routineId: routine.id,
        routineRef: routine.routineRef,
        routineName: routine.name,
        secretName,
      });
    }
  }

  return {
    pairs,
    locked: matched.map((one) => ({ routineId: one.routineId, secretName: one.secretName })),
    cells: ordered.length * secretNames.length,
    decided: closed.size,
  };
}

/**
 * Read back every cell this diagnostic has ever decided, for one account.
 *
 * The log is the durable half of the search: a decided cell is never revisited,
 * across runs, restarts and deploys. It is append-only and carries no secret
 * value — the secret's *name* and the outcome, which is what a later reader
 * needs and all they may have.
 */
export async function decidedPairs(routineIds: string[]): Promise<DecidedPair[]> {
  if (routineIds.length === 0) return [];
  const events = await listIdentityEvents({ action: ACTION, limit: 500 });
  const wanted = new Set(routineIds);
  const out: DecidedPair[] = [];
  for (const event of events) {
    if (!event.targetId || !wanted.has(event.targetId)) continue;
    const meta = event.metadata as { secretName?: unknown; outcome?: unknown };
    const secretName = typeof meta.secretName === 'string' ? meta.secretName : null;
    const outcome = typeof meta.outcome === 'string' ? meta.outcome : null;
    if (!secretName || !outcome) continue;
    if (outcome !== 'ELIMINATED' && outcome !== 'MATCHED') continue;
    out.push({ routineId: event.targetId, secretName, outcome });
  }
  return out;
}

/** Persist one cell's answer. Names and categories only; never a value. */
export async function recordPairAttempt(verdict: PairVerdict, actor: string): Promise<void> {
  await recordIdentityEvent({
    actorType: 'SYSTEM',
    actorId: actor,
    action: ACTION,
    targetType: 'FLEET_ROUTINE',
    targetId: verdict.routineId,
    result: verdict.outcome === 'MATCHED' ? 'SUCCESS' : 'DENIED',
    metadata: {
      routineRef: verdict.routineRef,
      secretName: verdict.secretName,
      outcome: verdict.outcome,
      kind: verdict.kind,
      detail: verdict.detail,
    },
  });
}

/**
 * Ask the provider about exactly one pairing.
 *
 * The one impure step, and the only place a bearer is read — out of the
 * environment by name, into `fireRoutine`'s `Authorization` header, and nowhere
 * else. The outcome is the provider's own answer translated into a fact about
 * the *cell*, which is a deliberately narrower claim than the fire's own
 * category: `AUTH` closes a cell, everything else either stops the search for
 * that trigger or says nothing at all.
 */
export async function tryPair(pair: Pair, routine: FleetRoutine): Promise<PairVerdict> {
  const token = resolveToken(pair.secretName);
  if (!token) {
    return {
      ...pair,
      outcome: 'SECRET_ABSENT',
      kind: null,
      detail: `the deployment has no variable named ${pair.secretName}, so there is nothing to test with.`,
    };
  }
  const outcome = await fireRoutine({
    target: {
      routineId: pair.routineRef,
      token,
      baseUrl: routine.baseUrl,
      routineVersion: routine.routineVersion,
    },
  });
  if (outcome.ok) {
    return {
      ...pair,
      outcome: 'MATCHED',
      kind: null,
      detail:
        `the provider accepted this bearer for this trigger and created session ` +
        `${outcome.sessionRef ?? 'with no id reported'}.`,
    };
  }
  if (outcome.kind === 'AUTH') {
    return { ...pair, outcome: 'ELIMINATED', kind: 'AUTH', detail: outcome.message };
  }
  return { ...pair, outcome: 'INCONCLUSIVE', kind: outcome.kind, detail: outcome.message };
}

/**
 * Whether a verdict means the search should stop asking about this trigger.
 *
 * `NOT_FOUND` and `PAUSED` are facts about the trigger rather than the bearer,
 * so no further bearer tells you anything; a rate limit or a transport failure
 * is a fact about the moment, and continuing would spend the remaining cells
 * learning the same nothing. Everything else lets the search carry on.
 */
export function stopsTrigger(verdict: PairVerdict): boolean {
  return verdict.outcome === 'INCONCLUSIVE';
}

/** The credential digest of a named secret, for a repoint. Never the value. */
export function digestOfSecret(secretName: string): string | null {
  const value = resolveToken(secretName);
  return value ? credentialDigest(value) : null;
}
