-- ---------------------------------------------------------------------------
-- CLOUD BASELINE
--
-- The same schema the local chain arrives at after its twelve migrations,
-- expressed once for Postgres. It is generated from the SQLite schema rather
-- than written beside it (scripts/generate-pg-baseline.mjs), so the two cannot
-- drift into describing different things.
--
-- Four deliberate differences, and no others:
--
--   * every table carries `seq`, an identity column standing in for SQLite's
--     rowid. Thirty-odd queries order by it to break ties on equal timestamps,
--     and without it those orderings would be arbitrary rather than stable.
--   * columns holding serialized JSON stay `text`. jsonb would have the driver
--     return parsed objects where every repository expects a string; converting
--     a column and its mapper together is a later, deliberate migration.
--   * timestamps stay `text`, holding the same ISO-8601 UTC strings SQLite
--     holds. A timestamptz would re-interpret them on the way in and out, and
--     the point of this schema is that the values survive unchanged.
--   * a `nocase` collation is defined, so the three queries that compare a
--     canonical name case-insensitively read identically on both backends.
--     SQLite has `COLLATE NOCASE` built in; Postgres needs the collation to
--     exist, and a nondeterministic ICU one at strength level 2 is what gives
--     the same answer. Defining it here is what lets the repositories stay
--     free of `if (dialect === ...)`.
-- ---------------------------------------------------------------------------

-- Must exist before any table that might reference it, and before the first
-- query that uses it.
CREATE COLLATION IF NOT EXISTS nocase (
  provider = icu,
  locale = 'und-u-ks-level2',
  deterministic = false
);

CREATE TABLE audit_evidence (
  id                       text PRIMARY KEY,
  audit_id                 text NOT NULL,
  gap_id                   text,
  document_id              text,
  extraction_run_id        text,
  chunk_id                 text,
  document_label           text NOT NULL DEFAULT '',
  page_number              integer,
  quote                    text NOT NULL DEFAULT '',
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE audit_findings (
  id                       text PRIMARY KEY,
  audit_id                 text NOT NULL,
  finding_type             text NOT NULL,
  ordinal                  integer NOT NULL DEFAULT 0,
  content                  text NOT NULL,
  payload                  text NOT NULL DEFAULT '{}',
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE audit_gaps (
  id                       text PRIMARY KEY,
  audit_id                 text NOT NULL,
  ordinal                  integer NOT NULL DEFAULT 0,
  classification           text NOT NULL,
  title                    text NOT NULL,
  detail                   text NOT NULL DEFAULT '',
  owning_layer_id          text,
  owning_layer_name        text,
  justification            text NOT NULL DEFAULT '',
  research_question        text,
  expected_contribution    text,
  source_pass              text NOT NULL DEFAULT 'JUDGE',
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE audit_passes (
  id                       text PRIMARY KEY,
  audit_id                 text,
  pipeline_id              text NOT NULL,
  project_id               text NOT NULL,
  layer_id                 text,
  pass_key                 text NOT NULL,
  ordinal                  integer NOT NULL DEFAULT 0,
  provider                 text,
  model                    text,
  prompt                   text NOT NULL,
  raw_response             text,
  parsed                   text NOT NULL DEFAULT 'null',
  ok                       integer NOT NULL DEFAULT 0,
  error                    text,
  duration_ms              integer,
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE audits (
  id                       text PRIMARY KEY,
  project_id               text NOT NULL,
  layer_id                 text,
  run_id                   text,
  audited_document_id      text,
  verdict                  text NOT NULL,
  summary                  text NOT NULL DEFAULT '',
  confidence               double precision,
  synthesis_required       integer NOT NULL DEFAULT 0,
  freeze_eligible          integer NOT NULL DEFAULT 0,
  next_version             text,
  next_action              text,
  source                   text NOT NULL DEFAULT 'MANUAL',
  raw                      text NOT NULL DEFAULT '{}',
  created_at               text NOT NULL,
  mode                     text NOT NULL DEFAULT 'SINGLE_DOCUMENT',
  profile_id               text,
  foundational_gap_count   integer NOT NULL DEFAULT 0,
  targeted_research_runs_required integer NOT NULL DEFAULT 0,
  audited_document_ids     text NOT NULL DEFAULT '[]',
  provider                 text,
  model                    text,
  evidence_manifest        text NOT NULL DEFAULT '{}',
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE boundary_contracts (
  id                       text PRIMARY KEY,
  orchestration_id         text NOT NULL,
  project_id               text NOT NULL,
  layer_id                 text NOT NULL,
  primary_question         text NOT NULL,
  decision_supported       text,
  audience                 text,
  included_subjects        text NOT NULL DEFAULT '[]',
  excluded_subjects        text NOT NULL DEFAULT '[]',
  geography                text,
  timeframe                text,
  population               text,
  definitions              text NOT NULL DEFAULT '[]',
  required_comparisons     text NOT NULL DEFAULT '[]',
  required_calculations    text NOT NULL DEFAULT '[]',
  expected_output          text,
  required_confidence      text,
  acceptable_uncertainty   text,
  prohibited_assumptions   text NOT NULL DEFAULT '[]',
  source_constraints       text NOT NULL DEFAULT '[]',
  completion_standard      text,
  ambiguities              text NOT NULL DEFAULT '[]',
  status                   text NOT NULL DEFAULT 'DRAFT',
  approved_at              text,
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE conversations (
  id                       text PRIMARY KEY,
  project_id               text NOT NULL,
  layer_id                 text,
  run_id                   text,
  title                    text NOT NULL,
  provider_conversation_id text,
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE dependencies (
  id                       text PRIMARY KEY,
  project_id               text NOT NULL,
  dependent_document_id    text,
  dependent_run_id         text,
  required_document_id     text,
  required_canonical_name  text NOT NULL,
  required_layer_id        text,
  dependency_type          text NOT NULL DEFAULT 'SOURCE_PACKET',
  required                 integer NOT NULL DEFAULT 1,
  notes                    text,
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY,
  CHECK (dependent_document_id IS NOT NULL OR dependent_run_id IS NOT NULL)
);

CREATE TABLE document_blocks (
  id                       text PRIMARY KEY,
  extraction_run_id        text NOT NULL,
  document_id              text NOT NULL,
  page_number              integer NOT NULL,
  block_index              integer NOT NULL,
  block_type               text NOT NULL DEFAULT 'PARAGRAPH',
  raw_text                 text NOT NULL,
  normalized_text          text NOT NULL,
  char_start               integer NOT NULL DEFAULT 0,
  char_end                 integer NOT NULL DEFAULT 0,
  extraction_method        text NOT NULL,
  confidence               double precision,
  warnings                 text NOT NULL DEFAULT '[]',
  content_hash             text NOT NULL,
  bbox                     text,
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE document_chunks (
  id                       text PRIMARY KEY,
  extraction_run_id        text NOT NULL,
  document_id              text NOT NULL,
  chunk_index              integer NOT NULL,
  page_start               integer NOT NULL,
  page_end                 integer NOT NULL,
  block_start              integer NOT NULL,
  block_end                integer NOT NULL,
  heading_path             text NOT NULL DEFAULT '[]',
  text                     text NOT NULL,
  char_count               integer NOT NULL DEFAULT 0,
  char_start               integer NOT NULL DEFAULT 0,
  char_end                 integer NOT NULL DEFAULT 0,
  overlap_prev             integer NOT NULL DEFAULT 0,
  has_ocr                  integer NOT NULL DEFAULT 0,
  content_hash             text NOT NULL,
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE document_findings (
  id                       text PRIMARY KEY,
  extraction_run_id        text NOT NULL,
  document_id              text NOT NULL,
  chunk_id                 text,
  finding_type             text NOT NULL,
  ordinal                  integer NOT NULL DEFAULT 0,
  content                  text NOT NULL,
  evidence_page            integer,
  evidence_quote           text NOT NULL DEFAULT '',
  confidence               double precision,
  source                   text NOT NULL DEFAULT 'PROVIDER',
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE document_segments (
  id                       text PRIMARY KEY,
  document_id              text NOT NULL,
  extraction_run_id        text NOT NULL,
  segment_index            integer NOT NULL,
  segment_type             text NOT NULL DEFAULT 'CONVERSATION',
  title                    text NOT NULL DEFAULT '',
  speaker                  text,
  timestamp_text           text,
  block_start              integer NOT NULL DEFAULT 0,
  block_end                integer NOT NULL DEFAULT 0,
  char_start               integer NOT NULL DEFAULT 0,
  char_end                 integer NOT NULL DEFAULT 0,
  text                     text NOT NULL,
  content_hash             text NOT NULL,
  confidence               double precision NOT NULL DEFAULT 0,
  rationale                text NOT NULL DEFAULT '',
  warnings                 text NOT NULL DEFAULT '[]',
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE documents (
  id                       text PRIMARY KEY,
  project_id               text NOT NULL,
  layer_id                 text,
  canonical_name           text NOT NULL,
  version                  text NOT NULL,
  version_sort             text NOT NULL,
  wave                     integer,
  document_type            text NOT NULL,
  status                   text NOT NULL DEFAULT 'EXPECTED',
  filename                 text,
  filesystem_path          text,
  file_size                integer,
  file_hash                text,
  file_missing             integer NOT NULL DEFAULT 0,
  conversation_title       text,
  source_run_id            text,
  parent_document_id       text,
  superseded_by_document_id text,
  is_canonical             integer NOT NULL DEFAULT 0,
  frozen                   integer NOT NULL DEFAULT 0,
  notes                    text,
  imported_at              text,
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  mime_type                text,
  detected_format          text,
  page_count               integer,
  extraction_status        text NOT NULL DEFAULT 'QUEUED',
  extraction_run_id        text,
  pipeline_version         text,
  origin                   text NOT NULL DEFAULT 'UPLOAD',
  scope                    text NOT NULL DEFAULT 'LAYER',
  classification_source    text,
  classification_confidence double precision,
  import_job_id            text,
  source_path              text,
  source_modified_at       text,
  storage_key              text,
  storage_provider         text,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE existing_claims (
  id                       text PRIMARY KEY,
  project_id               text NOT NULL,
  document_id              text NOT NULL,
  extraction_run_id        text,
  layer_id                 text,
  claim                    text NOT NULL,
  claim_type               text NOT NULL DEFAULT 'UNSUPPORTED_ASSERTION',
  page                     integer,
  block_index              integer,
  char_start               integer,
  char_end                 integer,
  locator                  text,
  source_url               text,
  source_title             text,
  source_publisher         text,
  source_date              text,
  retrieved_at             text,
  supporting_passage       text,
  geography                text,
  timeframe                text,
  population               text,
  definition               text,
  extraction_confidence    double precision NOT NULL DEFAULT 0,
  evidence_confidence      double precision NOT NULL DEFAULT 0,
  contradiction_state      text NOT NULL DEFAULT 'UNCHALLENGED',
  verification_state       text NOT NULL DEFAULT 'UNVERIFIED',
  verification_detail      text,
  prior_audit_id           text,
  document_version         text,
  superseded               integer NOT NULL DEFAULT 0,
  content_hash             text NOT NULL,
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE extraction_runs (
  id                       text PRIMARY KEY,
  document_id              text NOT NULL,
  project_id               text NOT NULL,
  status                   text NOT NULL DEFAULT 'QUEUED',
  pipeline_version         text NOT NULL,
  detected_format          text,
  source_hash              text,
  pages_expected           integer NOT NULL DEFAULT 0,
  pages_readable           integer NOT NULL DEFAULT 0,
  pages_ocr                integer NOT NULL DEFAULT 0,
  pages_failed             text NOT NULL DEFAULT '[]',
  character_count          integer NOT NULL DEFAULT 0,
  coverage_ratio           double precision NOT NULL DEFAULT 0,
  warnings                 text NOT NULL DEFAULT '[]',
  blocked_reason           text,
  error                    text,
  superseded_by_run_id     text,
  started_at               text,
  completed_at             text,
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  ocr_engine               text,
  ocr_engine_version       text,
  ocr_renderer_version     text,
  ocr_pages                text NOT NULL DEFAULT '[]',
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE import_files (
  id                       text PRIMARY KEY,
  job_id                   text NOT NULL,
  project_id               text NOT NULL,
  absolute_path            text NOT NULL,
  relative_path            text NOT NULL,
  filename                 text NOT NULL,
  file_size                integer,
  file_hash                text,
  detected_format          text,
  source_modified_at       text,
  status                   text NOT NULL DEFAULT 'DISCOVERED',
  document_id              text,
  duplicate_of_id          text,
  extraction_status        text,
  extraction_method        text,
  pages                    integer,
  ocr_pages                integer,
  detail                   text,
  warnings                 text NOT NULL DEFAULT '[]',
  classification           text,
  needs_confirmation       integer NOT NULL DEFAULT 0,
  attempts                 integer NOT NULL DEFAULT 0,
  started_at               text,
  completed_at             text,
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE import_jobs (
  id                       text PRIMARY KEY,
  project_id               text NOT NULL,
  source_label             text NOT NULL,
  root_path                text NOT NULL,
  status                   text NOT NULL DEFAULT 'DISCOVERING',
  scope                    text NOT NULL DEFAULT 'LAYER',
  discovered               integer NOT NULL DEFAULT 0,
  processed                integer NOT NULL DEFAULT 0,
  registered               integer NOT NULL DEFAULT 0,
  duplicates               integer NOT NULL DEFAULT 0,
  unsupported              integer NOT NULL DEFAULT 0,
  unreadable               integer NOT NULL DEFAULT 0,
  failed                   integer NOT NULL DEFAULT 0,
  needs_review             integer NOT NULL DEFAULT 0,
  message                  text,
  cancel_reason            text,
  heartbeat_at             text,
  started_at               text,
  completed_at             text,
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE ingestion_reports (
  id                       text PRIMARY KEY,
  document_id              text NOT NULL,
  extraction_run_id        text NOT NULL,
  scope                    text NOT NULL,
  report                   text NOT NULL,
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE layers (
  id                       text PRIMARY KEY,
  project_id               text NOT NULL,
  slug                     text NOT NULL,
  name                     text NOT NULL,
  order_index              integer NOT NULL,
  status                   text NOT NULL DEFAULT 'NOT_STARTED',
  status_source            text NOT NULL DEFAULT 'DERIVED',
  manual_status            text,
  manual_status_reason     text,
  current_version          text,
  current_wave             integer NOT NULL DEFAULT 1,
  canonical_document_id    text,
  expected_versions        text NOT NULL DEFAULT '[]',
  parked                   integer NOT NULL DEFAULT 0,
  parked_note              text,
  notes                    text,
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE messages (
  id                       text PRIMARY KEY,
  conversation_id          text NOT NULL,
  role                     text NOT NULL,
  content                  text NOT NULL,
  metadata                 text NOT NULL DEFAULT '{}',
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE project_events (
  id                       text PRIMARY KEY,
  project_id               text NOT NULL,
  layer_id                 text,
  entity_type              text NOT NULL,
  entity_id                text,
  event_type               text NOT NULL,
  payload                  text NOT NULL DEFAULT '{}',
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE projects (
  id                       text PRIMARY KEY,
  slug                     text NOT NULL,
  name                     text NOT NULL,
  description              text,
  north_star               text,
  current_wave             integer NOT NULL DEFAULT 1,
  status                   text NOT NULL DEFAULT 'ACTIVE',
  version_policy           text NOT NULL DEFAULT '{}',
  settings                 text NOT NULL DEFAULT '{}',
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE provider_connections (
  provider                 text PRIMARY KEY,
  installed                integer NOT NULL DEFAULT 0,
  authenticated            integer NOT NULL DEFAULT 0,
  automation_ready         integer NOT NULL DEFAULT 0,
  executable_path          text,
  version                  text,
  model                    text,
  quota_state              text,
  message                  text,
  diagnostics              text,
  last_checked_at          text,
  last_success_at          text,
  last_failure_at          text,
  last_failure_reason      text,
  paid_overage_enabled     integer NOT NULL DEFAULT 0,
  paid_overage_note        text,
  paid_overage_set_at      text,
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  light_model              text,
  verified_run_at          text,
  verified_run_detail      text,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE quota_pauses (
  id                       text PRIMARY KEY,
  orchestration_id         text,
  provider                 text NOT NULL,
  quota_state              text NOT NULL,
  detail                   text NOT NULL,
  jobs_completed           integer NOT NULL DEFAULT 0,
  jobs_pending             integer NOT NULL DEFAULT 0,
  paused_at                text NOT NULL,
  resumed_at               text,
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE requirement_coverage (
  id                       text PRIMARY KEY,
  orchestration_id         text NOT NULL,
  requirement_id           text NOT NULL,
  status                   text NOT NULL DEFAULT 'MISSING',
  reasons                  text NOT NULL DEFAULT '[]',
  claim_ids                text NOT NULL DEFAULT '[]',
  document_ids             text NOT NULL DEFAULT '[]',
  confidence               double precision NOT NULL DEFAULT 0,
  gap_type                 text,
  gap_detail               text,
  needs_research           integer NOT NULL DEFAULT 0,
  user_override            text,
  overridden_at            text,
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE requirements (
  id                       text PRIMARY KEY,
  orchestration_id         text NOT NULL,
  project_id               text NOT NULL,
  layer_id                 text NOT NULL,
  requirement_key          text NOT NULL,
  ordinal                  integer NOT NULL DEFAULT 0,
  statement                text NOT NULL,
  necessity                text NOT NULL DEFAULT 'MANDATORY',
  kind                     text NOT NULL DEFAULT 'RESEARCH',
  rationale                text,
  required_evidence        text NOT NULL DEFAULT '[]',
  completion_criteria      text NOT NULL DEFAULT '[]',
  depends_on               text NOT NULL DEFAULT '[]',
  owning_layer_id          text,
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE research_claims (
  id                       text PRIMARY KEY,
  orchestration_id         text NOT NULL,
  fragment_id              text,
  pass_id                  text,
  pass_key                 text NOT NULL,
  claim                    text NOT NULL,
  source_url               text,
  source_title             text,
  source_publisher         text,
  source_date              text,
  evidence_excerpt         text,
  evidence_locator         text,
  evidence_lane            text,
  retrieved_at             text,
  confidence               double precision NOT NULL DEFAULT 0,
  contradiction_state      text NOT NULL DEFAULT 'UNCHALLENGED',
  contradiction_note       text,
  validation_state         text NOT NULL DEFAULT 'NO_URL',
  validation_detail        text,
  sourced                  integer NOT NULL DEFAULT 0,
  derived                  integer NOT NULL DEFAULT 0,
  derived_from             text NOT NULL DEFAULT '[]',
  accepted                 integer NOT NULL DEFAULT 0,
  rejection_reason         text,
  scope_match              text,
  content_hash             text NOT NULL,
  created_at               text NOT NULL,
  claim_type               text NOT NULL DEFAULT 'SOURCED_FACT',
  source_group             text,
  primary_source           integer NOT NULL DEFAULT 0,
  geography                text,
  timeframe                text,
  population               text,
  definition               text,
  requirement_ids          text NOT NULL DEFAULT '[]',
  job_id                   text,
  reconciliation           text,
  reconciled_claim_id      text,
  contradiction_kind       text,
  reconciliation_detail    text,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE research_fragments (
  id                       text PRIMARY KEY,
  orchestration_id         text NOT NULL,
  project_id               text NOT NULL,
  layer_id                 text NOT NULL,
  fragment_index           integer NOT NULL,
  fragment_key             text NOT NULL,
  question                 text NOT NULL,
  geography                text,
  timeframe                text,
  population               text,
  definitions              text,
  required_evidence        text NOT NULL DEFAULT '[]',
  acceptable_source_types  text NOT NULL DEFAULT '[]',
  excluded_source_types    text NOT NULL DEFAULT '[]',
  completion_criteria      text NOT NULL DEFAULT '[]',
  depends_on               text NOT NULL DEFAULT '[]',
  min_independent_sources  integer NOT NULL DEFAULT 2,
  status                   text NOT NULL DEFAULT 'PLANNED',
  attempt                  integer NOT NULL DEFAULT 1,
  parent_fragment_id       text,
  repair_reason            text,
  repair_strategy          text,
  integrity_verdict        text,
  sufficiency_verdict      text,
  verdict_detail           text,
  blocked_reason           text,
  queued_at                text,
  started_at               text,
  completed_at             text,
  accepted_at              text,
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  requirement_ids          text NOT NULL DEFAULT '[]',
  evidence_lane            text,
  why_it_matters           text,
  missing_evidence         text,
  why_existing_insufficient text,
  existing_claim_ids       text NOT NULL DEFAULT '[]',
  excluded_scope           text,
  expected_claim_types     text NOT NULL DEFAULT '[]',
  preferred_source_types   text NOT NULL DEFAULT '[]',
  prohibited_evidence      text NOT NULL DEFAULT '[]',
  required_comparisons     text NOT NULL DEFAULT '[]',
  required_calculations    text NOT NULL DEFAULT '[]',
  contradiction_targets    text NOT NULL DEFAULT '[]',
  failure_conditions       text NOT NULL DEFAULT '[]',
  uncertainty_tolerance    text,
  priority                 integer NOT NULL DEFAULT 5,
  estimated_effort         text,
  max_repairs              integer NOT NULL DEFAULT 2,
  split_from_id            text,
  repair_plan              text,
  cancelled_reason         text,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE research_job_fragments (
  job_id                   text NOT NULL,
  fragment_id              text NOT NULL,
  ordinal                  integer NOT NULL DEFAULT 0,
  outcome                  text,
  detail                   text,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY,
  PRIMARY KEY (job_id, fragment_id)
);

CREATE TABLE research_jobs (
  id                       text PRIMARY KEY,
  orchestration_id         text NOT NULL,
  project_id               text NOT NULL,
  rationale                text NOT NULL DEFAULT '',
  provider                 text NOT NULL,
  model                    text,
  job_kind                 text NOT NULL DEFAULT 'INVESTIGATION',
  status                   text NOT NULL DEFAULT 'QUEUED',
  priority                 integer NOT NULL DEFAULT 5,
  external_job_id          text,
  prompt_sha256            text,
  prompt_bytes             integer,
  output_bytes             integer,
  duration_ms              integer,
  failure_reason           text,
  queued_at                text NOT NULL,
  started_at               text,
  completed_at             text,
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE research_orchestrations (
  id                       text PRIMARY KEY,
  project_id               text NOT NULL,
  layer_id                 text NOT NULL,
  run_id                   text NOT NULL,
  title                    text NOT NULL,
  assignment               text NOT NULL,
  target_version           text,
  provider                 text NOT NULL,
  model                    text,
  status                   text NOT NULL DEFAULT 'QUEUED',
  current_pass             text,
  attempt                  integer NOT NULL DEFAULT 1,
  parent_orchestration_id  text,
  repair_reason            text,
  report_text              text,
  document_id              text,
  audit_id                 text,
  verdict                  text,
  queued_at                text NOT NULL,
  started_at               text,
  completed_at             text,
  failed_at                text,
  failure_reason           text,
  cancelled_at             text,
  cancel_reason            text,
  heartbeat_at             text,
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  auto_approve             integer NOT NULL DEFAULT 1,
  approved_at              text,
  approval_note            text,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE research_passes (
  id                       text PRIMARY KEY,
  orchestration_id         text NOT NULL,
  fragment_id              text,
  pass_key                 text NOT NULL,
  ordinal                  integer NOT NULL,
  attempt                  integer NOT NULL DEFAULT 1,
  status                   text NOT NULL DEFAULT 'RUNNING',
  provider                 text NOT NULL,
  model                    text,
  prompt                   text NOT NULL,
  prompt_sha256            text NOT NULL,
  raw_response             text,
  parsed                   text,
  error                    text,
  job_id                   text,
  started_at               text NOT NULL,
  completed_at             text,
  duration_ms              integer,
  bundle_id                text,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE research_runs (
  id                       text PRIMARY KEY,
  project_id               text NOT NULL,
  layer_id                 text,
  target_document_id       text,
  target_version           text,
  run_type                 text NOT NULL,
  attempt_number           integer NOT NULL DEFAULT 1,
  status                   text NOT NULL DEFAULT 'PLANNED',
  provider                 text,
  model                    text,
  prompt                   text,
  prompt_sections          text NOT NULL DEFAULT '[]',
  required_attachments     text NOT NULL DEFAULT '[]',
  expected_conversation_title text,
  expected_filename        text,
  result_text              text,
  started_at               text,
  completed_at             text,
  failed_at                text,
  failure_reason           text,
  parent_run_id            text,
  redo_reason              text,
  dependency_override      integer NOT NULL DEFAULT 0,
  dependency_override_reason text,
  external_response_id     text,
  conversation_id          text,
  created_at               text NOT NULL,
  updated_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE segment_layer_links (
  id                       text PRIMARY KEY,
  document_id              text NOT NULL,
  segment_id               text,
  layer_id                 text NOT NULL,
  version                  text,
  link_type                text NOT NULL DEFAULT 'REFERENCE',
  confidence               double precision NOT NULL DEFAULT 0,
  rationale                text NOT NULL DEFAULT '',
  status                   text NOT NULL DEFAULT 'PROPOSED',
  decided_at               text,
  created_at               text NOT NULL,
  seq                      bigint GENERATED BY DEFAULT AS IDENTITY
);

-- Referential integrity, added once every table exists.
--
-- DEFERRABLE INITIALLY IMMEDIATE: checked per statement exactly as before,
-- so ordinary operation is unchanged and a broken reference still fails at
-- the statement that made it. What it adds is that a bulk loader may say
-- SET CONSTRAINTS ALL DEFERRED inside its own transaction — which the cloud
-- migration does, because this schema has self-references and cycles
-- (a run points at a document, a document at its parent, an orchestration
-- at an audit) and no table ordering exists that satisfies them all.
ALTER TABLE audit_evidence ADD CONSTRAINT audit_evidence_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES audits(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE audit_evidence ADD CONSTRAINT audit_evidence_gap_id_fkey FOREIGN KEY (gap_id) REFERENCES audit_gaps(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE audit_evidence ADD CONSTRAINT audit_evidence_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE audit_evidence ADD CONSTRAINT audit_evidence_extraction_run_id_fkey FOREIGN KEY (extraction_run_id) REFERENCES extraction_runs(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE audit_evidence ADD CONSTRAINT audit_evidence_chunk_id_fkey FOREIGN KEY (chunk_id) REFERENCES document_chunks(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE audit_findings ADD CONSTRAINT audit_findings_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES audits(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE audit_gaps ADD CONSTRAINT audit_gaps_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES audits(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE audit_gaps ADD CONSTRAINT audit_gaps_owning_layer_id_fkey FOREIGN KEY (owning_layer_id) REFERENCES layers(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE audit_passes ADD CONSTRAINT audit_passes_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES audits(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE audit_passes ADD CONSTRAINT audit_passes_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE audit_passes ADD CONSTRAINT audit_passes_layer_id_fkey FOREIGN KEY (layer_id) REFERENCES layers(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE audits ADD CONSTRAINT audits_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE audits ADD CONSTRAINT audits_layer_id_fkey FOREIGN KEY (layer_id) REFERENCES layers(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE audits ADD CONSTRAINT audits_run_id_fkey FOREIGN KEY (run_id) REFERENCES research_runs(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE audits ADD CONSTRAINT audits_audited_document_id_fkey FOREIGN KEY (audited_document_id) REFERENCES documents(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE boundary_contracts ADD CONSTRAINT boundary_contracts_orchestration_id_fkey FOREIGN KEY (orchestration_id) REFERENCES research_orchestrations(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE boundary_contracts ADD CONSTRAINT boundary_contracts_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE boundary_contracts ADD CONSTRAINT boundary_contracts_layer_id_fkey FOREIGN KEY (layer_id) REFERENCES layers(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE conversations ADD CONSTRAINT conversations_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE conversations ADD CONSTRAINT conversations_layer_id_fkey FOREIGN KEY (layer_id) REFERENCES layers(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE conversations ADD CONSTRAINT conversations_run_id_fkey FOREIGN KEY (run_id) REFERENCES research_runs(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dependencies ADD CONSTRAINT dependencies_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dependencies ADD CONSTRAINT dependencies_dependent_document_id_fkey FOREIGN KEY (dependent_document_id) REFERENCES documents(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dependencies ADD CONSTRAINT dependencies_dependent_run_id_fkey FOREIGN KEY (dependent_run_id) REFERENCES research_runs(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dependencies ADD CONSTRAINT dependencies_required_document_id_fkey FOREIGN KEY (required_document_id) REFERENCES documents(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE dependencies ADD CONSTRAINT dependencies_required_layer_id_fkey FOREIGN KEY (required_layer_id) REFERENCES layers(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE document_blocks ADD CONSTRAINT document_blocks_extraction_run_id_fkey FOREIGN KEY (extraction_run_id) REFERENCES extraction_runs(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE document_blocks ADD CONSTRAINT document_blocks_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE document_chunks ADD CONSTRAINT document_chunks_extraction_run_id_fkey FOREIGN KEY (extraction_run_id) REFERENCES extraction_runs(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE document_chunks ADD CONSTRAINT document_chunks_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE document_findings ADD CONSTRAINT document_findings_extraction_run_id_fkey FOREIGN KEY (extraction_run_id) REFERENCES extraction_runs(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE document_findings ADD CONSTRAINT document_findings_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE document_findings ADD CONSTRAINT document_findings_chunk_id_fkey FOREIGN KEY (chunk_id) REFERENCES document_chunks(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE document_segments ADD CONSTRAINT document_segments_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE document_segments ADD CONSTRAINT document_segments_extraction_run_id_fkey FOREIGN KEY (extraction_run_id) REFERENCES extraction_runs(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE documents ADD CONSTRAINT documents_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE documents ADD CONSTRAINT documents_layer_id_fkey FOREIGN KEY (layer_id) REFERENCES layers(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE documents ADD CONSTRAINT documents_parent_document_id_fkey FOREIGN KEY (parent_document_id) REFERENCES documents(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE documents ADD CONSTRAINT documents_superseded_by_document_id_fkey FOREIGN KEY (superseded_by_document_id) REFERENCES documents(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE existing_claims ADD CONSTRAINT existing_claims_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE existing_claims ADD CONSTRAINT existing_claims_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE existing_claims ADD CONSTRAINT existing_claims_extraction_run_id_fkey FOREIGN KEY (extraction_run_id) REFERENCES extraction_runs(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE existing_claims ADD CONSTRAINT existing_claims_layer_id_fkey FOREIGN KEY (layer_id) REFERENCES layers(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE existing_claims ADD CONSTRAINT existing_claims_prior_audit_id_fkey FOREIGN KEY (prior_audit_id) REFERENCES audits(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE extraction_runs ADD CONSTRAINT extraction_runs_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE extraction_runs ADD CONSTRAINT extraction_runs_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE extraction_runs ADD CONSTRAINT extraction_runs_superseded_by_run_id_fkey FOREIGN KEY (superseded_by_run_id) REFERENCES extraction_runs(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE import_files ADD CONSTRAINT import_files_job_id_fkey FOREIGN KEY (job_id) REFERENCES import_jobs(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE import_files ADD CONSTRAINT import_files_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE import_files ADD CONSTRAINT import_files_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE import_files ADD CONSTRAINT import_files_duplicate_of_id_fkey FOREIGN KEY (duplicate_of_id) REFERENCES documents(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE import_jobs ADD CONSTRAINT import_jobs_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ingestion_reports ADD CONSTRAINT ingestion_reports_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE ingestion_reports ADD CONSTRAINT ingestion_reports_extraction_run_id_fkey FOREIGN KEY (extraction_run_id) REFERENCES extraction_runs(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE layers ADD CONSTRAINT layers_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE messages ADD CONSTRAINT messages_conversation_id_fkey FOREIGN KEY (conversation_id) REFERENCES conversations(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE project_events ADD CONSTRAINT project_events_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE quota_pauses ADD CONSTRAINT quota_pauses_orchestration_id_fkey FOREIGN KEY (orchestration_id) REFERENCES research_orchestrations(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE requirement_coverage ADD CONSTRAINT requirement_coverage_orchestration_id_fkey FOREIGN KEY (orchestration_id) REFERENCES research_orchestrations(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE requirement_coverage ADD CONSTRAINT requirement_coverage_requirement_id_fkey FOREIGN KEY (requirement_id) REFERENCES requirements(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE requirements ADD CONSTRAINT requirements_orchestration_id_fkey FOREIGN KEY (orchestration_id) REFERENCES research_orchestrations(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE requirements ADD CONSTRAINT requirements_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE requirements ADD CONSTRAINT requirements_layer_id_fkey FOREIGN KEY (layer_id) REFERENCES layers(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE requirements ADD CONSTRAINT requirements_owning_layer_id_fkey FOREIGN KEY (owning_layer_id) REFERENCES layers(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_claims ADD CONSTRAINT research_claims_orchestration_id_fkey FOREIGN KEY (orchestration_id) REFERENCES research_orchestrations(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_claims ADD CONSTRAINT research_claims_fragment_id_fkey FOREIGN KEY (fragment_id) REFERENCES research_fragments(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_claims ADD CONSTRAINT research_claims_pass_id_fkey FOREIGN KEY (pass_id) REFERENCES research_passes(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_fragments ADD CONSTRAINT research_fragments_orchestration_id_fkey FOREIGN KEY (orchestration_id) REFERENCES research_orchestrations(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_fragments ADD CONSTRAINT research_fragments_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_fragments ADD CONSTRAINT research_fragments_layer_id_fkey FOREIGN KEY (layer_id) REFERENCES layers(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_fragments ADD CONSTRAINT research_fragments_parent_fragment_id_fkey FOREIGN KEY (parent_fragment_id) REFERENCES research_fragments(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_job_fragments ADD CONSTRAINT research_job_fragments_job_id_fkey FOREIGN KEY (job_id) REFERENCES research_jobs(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_job_fragments ADD CONSTRAINT research_job_fragments_fragment_id_fkey FOREIGN KEY (fragment_id) REFERENCES research_fragments(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_jobs ADD CONSTRAINT research_jobs_orchestration_id_fkey FOREIGN KEY (orchestration_id) REFERENCES research_orchestrations(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_jobs ADD CONSTRAINT research_jobs_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_orchestrations ADD CONSTRAINT research_orchestrations_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_orchestrations ADD CONSTRAINT research_orchestrations_layer_id_fkey FOREIGN KEY (layer_id) REFERENCES layers(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_orchestrations ADD CONSTRAINT research_orchestrations_run_id_fkey FOREIGN KEY (run_id) REFERENCES research_runs(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_orchestrations ADD CONSTRAINT research_orchestrations_parent_orchestration_id_fkey FOREIGN KEY (parent_orchestration_id) REFERENCES research_orchestrations(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_orchestrations ADD CONSTRAINT research_orchestrations_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_orchestrations ADD CONSTRAINT research_orchestrations_audit_id_fkey FOREIGN KEY (audit_id) REFERENCES audits(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_passes ADD CONSTRAINT research_passes_orchestration_id_fkey FOREIGN KEY (orchestration_id) REFERENCES research_orchestrations(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_passes ADD CONSTRAINT research_passes_fragment_id_fkey FOREIGN KEY (fragment_id) REFERENCES research_fragments(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_runs ADD CONSTRAINT research_runs_project_id_fkey FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_runs ADD CONSTRAINT research_runs_layer_id_fkey FOREIGN KEY (layer_id) REFERENCES layers(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_runs ADD CONSTRAINT research_runs_target_document_id_fkey FOREIGN KEY (target_document_id) REFERENCES documents(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE research_runs ADD CONSTRAINT research_runs_parent_run_id_fkey FOREIGN KEY (parent_run_id) REFERENCES research_runs(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE segment_layer_links ADD CONSTRAINT segment_layer_links_document_id_fkey FOREIGN KEY (document_id) REFERENCES documents(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE segment_layer_links ADD CONSTRAINT segment_layer_links_segment_id_fkey FOREIGN KEY (segment_id) REFERENCES document_segments(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE segment_layer_links ADD CONSTRAINT segment_layer_links_layer_id_fkey FOREIGN KEY (layer_id) REFERENCES layers(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;

-- Indexes, exactly as the local chain declares them.
CREATE INDEX idx_audit_evidence_audit ON audit_evidence (audit_id);
CREATE INDEX idx_audit_evidence_gap ON audit_evidence (gap_id);
CREATE INDEX idx_audit_findings_audit ON audit_findings (audit_id, finding_type, ordinal);
CREATE INDEX idx_audit_gaps_audit ON audit_gaps (audit_id, ordinal);
CREATE INDEX idx_audit_gaps_classification ON audit_gaps (classification);
CREATE INDEX idx_audit_passes_audit ON audit_passes (audit_id, ordinal);
CREATE INDEX idx_audit_passes_pipeline ON audit_passes (pipeline_id, ordinal);
CREATE INDEX idx_audits_document ON audits (audited_document_id, created_at);
CREATE INDEX idx_audits_layer ON audits (layer_id, created_at);
CREATE INDEX idx_blocks_document ON document_blocks (document_id, page_number);
CREATE INDEX idx_blocks_run ON document_blocks (extraction_run_id, page_number, block_index);
CREATE INDEX idx_boundary_orchestration ON boundary_contracts (orchestration_id);
CREATE INDEX idx_chunks_document ON document_chunks (document_id, chunk_index);
CREATE INDEX idx_chunks_run ON document_chunks (extraction_run_id, chunk_index);
CREATE INDEX idx_conversations_project ON conversations (project_id, updated_at);
CREATE INDEX idx_coverage_orchestration ON requirement_coverage (orchestration_id, status);
CREATE UNIQUE INDEX idx_coverage_requirement ON requirement_coverage (orchestration_id, requirement_id);
CREATE INDEX idx_dependencies_document ON dependencies (dependent_document_id);
CREATE INDEX idx_dependencies_required ON dependencies (project_id, required_canonical_name);
CREATE INDEX idx_dependencies_run ON dependencies (dependent_run_id);
CREATE INDEX idx_doc_findings_chunk ON document_findings (chunk_id);
CREATE INDEX idx_doc_findings_run ON document_findings (extraction_run_id, finding_type, ordinal);
CREATE INDEX idx_documents_layer ON documents (layer_id, version_sort);
CREATE INDEX idx_documents_path ON documents (filesystem_path);
CREATE INDEX idx_documents_project ON documents (project_id, status);
CREATE INDEX idx_documents_storage_key ON documents (storage_key);
CREATE INDEX idx_events_entity ON project_events (entity_type, entity_id);
CREATE INDEX idx_events_layer ON project_events (layer_id, created_at DESC);
CREATE INDEX idx_events_project ON project_events (project_id, created_at DESC);
CREATE INDEX idx_existing_claims_hash ON existing_claims (project_id, content_hash);
CREATE INDEX idx_existing_claims_project ON existing_claims (project_id, document_id);
CREATE INDEX idx_extraction_runs_document ON extraction_runs (document_id, created_at DESC);
CREATE INDEX idx_extraction_runs_status ON extraction_runs (status);
CREATE INDEX idx_fragments_orchestration ON research_fragments (orchestration_id, fragment_index);
CREATE INDEX idx_fragments_parent ON research_fragments (parent_fragment_id);
CREATE INDEX idx_fragments_status ON research_fragments (status, queued_at);
CREATE INDEX idx_import_files_hash ON import_files (project_id, file_hash);
CREATE INDEX idx_import_files_job ON import_files (job_id, status);
CREATE UNIQUE INDEX idx_import_files_path ON import_files (job_id, relative_path);
CREATE INDEX idx_import_jobs_project ON import_jobs (project_id, status);
CREATE INDEX idx_ingestion_document ON ingestion_reports (document_id, created_at);
CREATE INDEX idx_job_fragments_fragment ON research_job_fragments (fragment_id);
CREATE INDEX idx_layers_project ON layers (project_id, order_index);
CREATE INDEX idx_links_document ON segment_layer_links (document_id, status);
CREATE INDEX idx_links_layer ON segment_layer_links (layer_id, status);
CREATE INDEX idx_links_segment ON segment_layer_links (segment_id);
CREATE INDEX idx_messages_conversation ON messages (conversation_id, created_at);
CREATE INDEX idx_orchestrations_layer ON research_orchestrations (layer_id, created_at);
CREATE INDEX idx_orchestrations_parent ON research_orchestrations (parent_orchestration_id);
CREATE INDEX idx_orchestrations_project ON research_orchestrations (project_id, status);
CREATE INDEX idx_orchestrations_run ON research_orchestrations (run_id);
CREATE INDEX idx_quota_pauses_orchestration ON quota_pauses (orchestration_id, paused_at);
CREATE UNIQUE INDEX idx_requirements_key ON requirements (orchestration_id, requirement_key);
CREATE INDEX idx_requirements_orchestration ON requirements (orchestration_id, ordinal);
CREATE INDEX idx_research_claims_fragment ON research_claims (fragment_id, accepted);
CREATE INDEX idx_research_claims_hash ON research_claims (orchestration_id, content_hash);
CREATE INDEX idx_research_claims_orchestration ON research_claims (orchestration_id, pass_key);
CREATE INDEX idx_research_jobs_orchestration ON research_jobs (orchestration_id, status);
CREATE INDEX idx_research_jobs_status ON research_jobs (status, priority, queued_at);
CREATE INDEX idx_research_passes_fragment ON research_passes (fragment_id, ordinal, attempt);
CREATE INDEX idx_research_passes_orchestration ON research_passes (orchestration_id, ordinal, attempt);
CREATE INDEX idx_runs_layer ON research_runs (layer_id, created_at);
CREATE INDEX idx_runs_parent ON research_runs (parent_run_id);
CREATE INDEX idx_runs_project_status ON research_runs (project_id, status);
CREATE INDEX idx_segments_document ON document_segments (document_id, segment_index);
CREATE INDEX idx_segments_run ON document_segments (extraction_run_id, segment_type);

