-- ---------------------------------------------------------------------------
-- IDENTITY, CREDENTIALS AND AUTHORIZATION
--
-- The Postgres counterpart of the local chain's 014_identity.sql. The two files
-- describe the same schema and differ only in the four ways the baseline
-- already documents: `seq` stands in for rowid, serialized JSON stays text,
-- timestamps stay text, and case-insensitive comparison uses the `nocase`
-- collation defined in the baseline.
--
-- Uniqueness is declared here as explicit unique indexes rather than inline
-- column constraints. That is a correction, not a preference: the generator
-- that produced 001_baseline.sql silently dropped SQLite's column-level UNIQUE,
-- so the cloud schema has been enforcing three fewer constraints than the local
-- one. 004_unique_parity.sql repairs that for the tables that predate this
-- migration; declaring them explicitly here is how these tables avoid inheriting
-- the same gap.
--
-- Nothing in this migration stores a secret. See 014_identity.sql for the
-- reasoning behind each table; it is not repeated here, because two copies of
-- an explanation are two things to keep in step.
-- ---------------------------------------------------------------------------

CREATE TABLE users (
  id                   text PRIMARY KEY,
  email                text NOT NULL,
  display_name         text NOT NULL,
  password_algorithm   text NOT NULL,
  password_verifier    text NOT NULL,
  password_updated_at  text NOT NULL,
  must_change_password integer NOT NULL DEFAULT 0,
  is_brain_admin       integer NOT NULL DEFAULT 0,
  disabled_at          text,
  created_by_type      text,
  created_by_id        text,
  created_at           text NOT NULL,
  updated_at           text NOT NULL,
  seq                  bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE user_sessions (
  id              text PRIMARY KEY,
  user_id         text NOT NULL,
  token_verifier  text NOT NULL,
  issued_at       text NOT NULL,
  expires_at      text NOT NULL,
  revoked_at      text,
  last_seen_at    text,
  user_agent      text,
  created_ip      text,
  seq             bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE workers (
  id              text PRIMARY KEY,
  name            text NOT NULL,
  display_name    text NOT NULL,
  worker_type     text NOT NULL DEFAULT 'GENERIC',
  description     text,
  status          text NOT NULL DEFAULT 'ACTIVE',
  disabled_at     text,
  created_by_type text NOT NULL,
  created_by_id   text NOT NULL,
  created_at      text NOT NULL,
  updated_at      text NOT NULL,
  seq             bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE worker_credentials (
  id              text PRIMARY KEY,
  worker_id       text NOT NULL,
  prefix          text NOT NULL,
  verifier        text NOT NULL,
  issued_at       text NOT NULL,
  expires_at      text,
  revoked_at      text,
  revoked_reason  text,
  last_used_at    text,
  issued_by_type  text NOT NULL,
  issued_by_id    text NOT NULL,
  rotated_from    text,
  seq             bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE project_memberships (
  id               text PRIMARY KEY,
  project_id       text NOT NULL,
  principal_type   text NOT NULL,
  principal_id     text NOT NULL,
  role             text,
  scopes           text NOT NULL DEFAULT '[]',
  granted_by_type  text NOT NULL,
  granted_by_id    text NOT NULL,
  granted_at       text NOT NULL,
  revoked_at       text,
  updated_at       text NOT NULL,
  seq              bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE TABLE identity_events (
  id            text PRIMARY KEY,
  created_at    text NOT NULL,
  actor_type    text NOT NULL,
  actor_id      text,
  credential_id text,
  action        text NOT NULL,
  target_type   text,
  target_id     text,
  project_id    text,
  result        text NOT NULL,
  reason        text,
  request_id    text,
  metadata      text NOT NULL DEFAULT '{}',
  user_agent    text,
  remote_addr   text,
  seq           bigint GENERATED BY DEFAULT AS IDENTITY
);

-- Uniqueness. These are the constraints authentication depends on: two users
-- with one email, or two credentials with one prefix, would make "which
-- principal is this" ambiguous, and an ambiguous principal is not a principal.
--
-- Named exactly as the generator names them (uq_<table>__<columns>) and guarded
-- with IF NOT EXISTS, so a database built from a regenerated baseline — which
-- carries them inline — and one built from this migration end up identical
-- rather than one of them failing on a name that already exists.
CREATE UNIQUE INDEX IF NOT EXISTS uq_users__email ON users (email);
CREATE UNIQUE INDEX IF NOT EXISTS uq_user_sessions__token_verifier ON user_sessions (token_verifier);
CREATE UNIQUE INDEX IF NOT EXISTS uq_workers__name ON workers (name);
CREATE UNIQUE INDEX IF NOT EXISTS uq_worker_credentials__prefix ON worker_credentials (prefix);
CREATE UNIQUE INDEX IF NOT EXISTS uq_project_memberships__project_id_principal_type_principal_id
  ON project_memberships (project_id, principal_type, principal_id);

CREATE INDEX idx_user_sessions_user ON user_sessions (user_id);
CREATE INDEX idx_user_sessions_expiry ON user_sessions (expires_at);
CREATE INDEX idx_worker_credentials_worker ON worker_credentials (worker_id);
CREATE INDEX idx_worker_credentials_live ON worker_credentials (revoked_at, expires_at);
CREATE INDEX idx_memberships_principal ON project_memberships (principal_type, principal_id);
CREATE INDEX idx_memberships_project ON project_memberships (project_id, revoked_at);
CREATE INDEX idx_identity_events_time ON identity_events (created_at DESC);
CREATE INDEX idx_identity_events_actor ON identity_events (actor_type, actor_id, created_at DESC);
CREATE INDEX idx_identity_events_project ON identity_events (project_id, created_at DESC);
CREATE INDEX idx_identity_events_action ON identity_events (action, created_at DESC);

-- Foreign keys, deferrable in the same way as every other one in this schema so
-- a bulk load can defer them without the constraint meaning anything different
-- during ordinary work.
--
-- identity_events deliberately has none: an audit row a cascade can delete is
-- not an audit row, and the record of who was given access to a project is most
-- interesting exactly when the project is gone.
ALTER TABLE user_sessions ADD CONSTRAINT user_sessions_user_id_fkey
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE worker_credentials ADD CONSTRAINT worker_credentials_worker_id_fkey
  FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE worker_credentials ADD CONSTRAINT worker_credentials_rotated_from_fkey
  FOREIGN KEY (rotated_from) REFERENCES worker_credentials(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE project_memberships ADD CONSTRAINT project_memberships_project_id_fkey
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
