-- ---------------------------------------------------------------------------
-- THE DISTRIBUTED WORK QUEUE
--
-- The Postgres counterpart of the local chain's 015_work_queue.sql. The two
-- describe the same schema and differ only in the four ways the baseline
-- documents: `seq` stands in for rowid, serialized JSON stays text, timestamps
-- stay text, and case-insensitive comparison uses the `nocase` collation.
--
-- Uniqueness is an explicit `uq_`-prefixed index, foreign keys are added by
-- ALTER after the tables exist, and both are named to match the local chain —
-- the convention 003_identity.sql established after the baseline generator was
-- found to have dropped three uniqueness constraints in translation.
--
-- The reasoning behind every column is in 015_work_queue.sql and is not
-- repeated, because two copies of an explanation are two things to keep in
-- step. The one thing worth saying twice: this schema does not rely on any
-- Postgres-only concurrency primitive. `FOR UPDATE SKIP LOCKED` exists here and
-- is deliberately unused — outside a transaction its row locks are released as
-- the statement ends, and inside one it would trade held locks for contention
-- avoidance this fleet does not yet need. What makes a claim atomic is the
-- compare-and-swap on `lease_generation`, and that runs identically on both
-- backends.
-- ---------------------------------------------------------------------------

CREATE TABLE work_items (
  id                   text PRIMARY KEY,
  project_id           text NOT NULL,
  work_type            text NOT NULL,
  state                text NOT NULL DEFAULT 'QUEUED',
  priority             integer NOT NULL DEFAULT 5,
  available_at         text NOT NULL,
  payload              text NOT NULL DEFAULT '{}',
  required_scopes      text NOT NULL DEFAULT '[]',
  target_worker_id     text,
  attempt_count        integer NOT NULL DEFAULT 0,
  max_attempts         integer NOT NULL DEFAULT 3,
  lease_generation     integer NOT NULL DEFAULT 0,
  lease_id             text,
  worker_id            text,
  lease_credential_id  text,
  leased_at            text,
  heartbeat_at         text,
  lease_expires_at     text,
  result_ref           text,
  result_summary       text,
  failure_category     text,
  cancelled_reason     text,
  correlation_id       text,
  created_by_type      text NOT NULL,
  created_by_id        text,
  created_at           text NOT NULL,
  updated_at           text NOT NULL,
  completed_at         text,
  seq                  bigint GENERATED BY DEFAULT AS IDENTITY,

  CHECK (state IN ('QUEUED', 'LEASED', 'SUCCEEDED', 'FAILED', 'CANCELLED')),
  CHECK (priority BETWEEN 0 AND 9),
  CHECK (attempt_count >= 0),
  CHECK (max_attempts >= 1),
  CHECK (lease_generation >= 0),
  CHECK (
    (state = 'LEASED'
       AND lease_id IS NOT NULL AND worker_id IS NOT NULL AND lease_expires_at IS NOT NULL)
    OR
    (state <> 'LEASED'
       AND lease_id IS NULL AND worker_id IS NULL AND lease_expires_at IS NULL)
  )
);

CREATE TABLE work_leases (
  id                 text PRIMARY KEY,
  work_item_id       text NOT NULL,
  project_id         text NOT NULL,
  attempt_number     integer NOT NULL,
  lease_generation   integer NOT NULL,
  worker_id          text NOT NULL,
  credential_id      text,
  claimed_at         text NOT NULL,
  expires_at         text NOT NULL,
  last_heartbeat_at  text,
  heartbeat_count    integer NOT NULL DEFAULT 0,
  ended_at           text,
  outcome            text,
  detail             text,
  request_id         text,
  seq                bigint GENERATED BY DEFAULT AS IDENTITY,

  CHECK (attempt_number >= 1),
  CHECK (heartbeat_count >= 0),
  CHECK (outcome IS NULL OR outcome IN ('SUCCEEDED', 'FAILED', 'EXPIRED', 'CANCELLED', 'RELEASED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_work_leases__work_item_id_lease_generation
  ON work_leases (work_item_id, lease_generation);

CREATE INDEX idx_work_items_claim
  ON work_items (state, project_id, priority DESC, available_at, created_at, id);
CREATE INDEX idx_work_items_expiry ON work_items (state, lease_expires_at);
CREATE INDEX idx_work_items_project ON work_items (project_id, state);
CREATE INDEX idx_work_items_worker ON work_items (worker_id, state);

CREATE INDEX idx_work_leases_item ON work_leases (work_item_id, lease_generation DESC);
CREATE INDEX idx_work_leases_worker ON work_leases (worker_id, claimed_at DESC);
CREATE INDEX idx_work_leases_open ON work_leases (ended_at, expires_at);

ALTER TABLE work_items ADD CONSTRAINT fk_work_items__project_id
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE work_items ADD CONSTRAINT fk_work_items__target_worker_id
  FOREIGN KEY (target_worker_id) REFERENCES workers(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE work_items ADD CONSTRAINT fk_work_items__worker_id
  FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE work_leases ADD CONSTRAINT fk_work_leases__work_item_id
  FOREIGN KEY (work_item_id) REFERENCES work_items(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE work_leases ADD CONSTRAINT fk_work_leases__project_id
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE work_leases ADD CONSTRAINT fk_work_leases__worker_id
  FOREIGN KEY (worker_id) REFERENCES workers(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
