-- ---------------------------------------------------------------------------
-- IDEMPOTENCY AND EFFECT CONTROL
--
-- The Postgres counterpart of the local chain's 016_idempotency.sql. The two
-- describe the same schema and differ only in the four ways the baseline
-- documents: `seq` stands in for rowid, serialized JSON stays text, timestamps
-- stay text, and case-insensitive comparison uses the `nocase` collation.
--
-- Uniqueness is an explicit `uq_`-prefixed index and foreign keys are added by
-- ALTER, per the convention 003_identity.sql established.
--
-- The reasoning behind every column is in 016_idempotency.sql and is not
-- repeated here. The one thing worth saying twice: the unique index on
-- (scope_hash, key_fingerprint) is not an optimisation. It is the entire
-- duplicate-suppression mechanism, and it works across Brain instances because
-- it lives in the database rather than in a process.
-- ---------------------------------------------------------------------------

CREATE TABLE idempotency_operations (
  id                  text PRIMARY KEY,
  scope_hash          text NOT NULL,
  key_fingerprint     text NOT NULL,
  namespace           text NOT NULL,
  namespace_version   integer NOT NULL DEFAULT 1,
  project_id          text NOT NULL,
  created_by_type     text NOT NULL,
  created_by_id       text,
  correlation_id      text,
  work_item_id        text,
  lease_generation    integer,
  request_fingerprint text NOT NULL,
  fingerprint_version integer NOT NULL DEFAULT 1,
  state               text NOT NULL DEFAULT 'RESERVED',
  attempt_count       integer NOT NULL DEFAULT 0,
  failure_category    text,
  uncertainty_reason  text,
  recover_after       text,
  result_ref          text,
  result_status       integer,
  result_summary      text,
  retention_class     text NOT NULL DEFAULT 'STANDARD',
  reserved_at         text NOT NULL,
  started_at          text,
  completed_at        text,
  created_at          text NOT NULL,
  updated_at          text NOT NULL,
  seq                 bigint GENERATED BY DEFAULT AS IDENTITY,

  CHECK (state IN ('RESERVED', 'SUCCEEDED', 'FAILED', 'UNCERTAIN')),
  CHECK (attempt_count >= 0),
  CHECK (namespace_version >= 1),
  CHECK (fingerprint_version >= 1),
  CHECK (state <> 'UNCERTAIN' OR uncertainty_reason IS NOT NULL),
  CHECK (state = 'RESERVED' OR recover_after IS NULL),
  CHECK ((state = 'RESERVED') = (completed_at IS NULL))
);

CREATE TABLE effect_attempts (
  id                text PRIMARY KEY,
  operation_id      text NOT NULL,
  attempt_number    integer NOT NULL,
  executor_type     text NOT NULL,
  executor_id       text,
  work_item_id      text,
  lease_id          text,
  lease_generation  integer,
  adapter           text,
  provider_key      text,
  phase             text NOT NULL DEFAULT 'INTENT',
  receipt_ref       text,
  receipt_meta      text NOT NULL DEFAULT '{}',
  started_at        text NOT NULL,
  ended_at          text,
  outcome           text,
  detail            text,
  request_id        text,
  seq               bigint GENERATED BY DEFAULT AS IDENTITY,

  CHECK (attempt_number >= 1),
  CHECK (phase IN ('INTENT', 'SENT', 'CONFIRMED', 'FAILED', 'UNCERTAIN')),
  CHECK (outcome IS NULL OR outcome IN ('SUCCEEDED', 'FAILED', 'UNCERTAIN', 'ABANDONED'))
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_idempotency_operations__scope_hash_key_fingerprint
  ON idempotency_operations (scope_hash, key_fingerprint);
CREATE UNIQUE INDEX IF NOT EXISTS uq_effect_attempts__operation_id_attempt_number
  ON effect_attempts (operation_id, attempt_number);

CREATE INDEX idx_idempotency_operations_project ON idempotency_operations (project_id, state);
CREATE INDEX idx_idempotency_operations_work_item ON idempotency_operations (work_item_id);
CREATE INDEX idx_idempotency_operations_recovery ON idempotency_operations (state, recover_after);
CREATE INDEX idx_idempotency_operations_retention ON idempotency_operations (retention_class, completed_at);

CREATE INDEX idx_effect_attempts_operation ON effect_attempts (operation_id, attempt_number DESC);
CREATE INDEX idx_effect_attempts_open ON effect_attempts (phase, ended_at);
CREATE INDEX idx_effect_attempts_provider ON effect_attempts (adapter, provider_key);

ALTER TABLE idempotency_operations ADD CONSTRAINT fk_idempotency_operations__project_id
  FOREIGN KEY (project_id) REFERENCES projects(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE idempotency_operations ADD CONSTRAINT fk_idempotency_operations__work_item_id
  FOREIGN KEY (work_item_id) REFERENCES work_items(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE effect_attempts ADD CONSTRAINT fk_effect_attempts__operation_id
  FOREIGN KEY (operation_id) REFERENCES idempotency_operations(id) ON DELETE CASCADE DEFERRABLE INITIALLY IMMEDIATE;
ALTER TABLE effect_attempts ADD CONSTRAINT fk_effect_attempts__work_item_id
  FOREIGN KEY (work_item_id) REFERENCES work_items(id) ON DELETE SET NULL DEFERRABLE INITIALLY IMMEDIATE;
