-- ---------------------------------------------------------------------------
-- CHECKPOINT SEQ
--
-- `work_item_checkpoints` was created in 010 without `seq`, and this chain's
-- baseline says in its own header that every table carries one. It is not a
-- decoration: `dialect.ts` rewrites `rowid` to `seq` when a query reaches
-- Postgres, so a table without the column is a table no query may order by
-- insertion on. Ordering by anything else is wrong for an append-only log —
-- timestamps are millisecond text and ids are random, so two notes written in
-- the same millisecond come back in an arbitrary order.
--
-- The omission was invisible until a query used it, which is the failure mode
-- worth recording: a schema difference between the two chains costs nothing
-- until the first statement that depends on it, and then it costs a deploy.
--
-- No local counterpart. SQLite gives every table a rowid without being asked,
-- which is exactly why this was easy to forget.
-- ---------------------------------------------------------------------------

ALTER TABLE work_item_checkpoints
  ADD COLUMN seq bigint GENERATED BY DEFAULT AS IDENTITY;
