-- The Postgres half of migration 024. See that file for the reasoning; this
-- chain is numbered independently and the two versions do not mean the same
-- thing.
--
-- The only deliberate differences are the ones this chain always has: every
-- table carries `seq`, the identity column standing in for SQLite's `rowid`,
-- and booleans are stored as integers so one repository layer reads both
-- backends identically.

CREATE TABLE bins (
  seq                   bigint GENERATED BY DEFAULT AS IDENTITY,
  id                    text PRIMARY KEY,
  project_id            text NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  layer_id              text REFERENCES layers(id) ON DELETE SET NULL,

  kind                  text NOT NULL,

  title                 text NOT NULL,
  objective             text NOT NULL,
  rationale             text,

  manifest              text NOT NULL DEFAULT '{}',

  completion_contract   text NOT NULL,
  contract_version      integer NOT NULL DEFAULT 1,

  state                 text NOT NULL DEFAULT 'DRAFT',
  priority              integer NOT NULL DEFAULT 5,

  orchestration_id      text REFERENCES research_orchestrations(id) ON DELETE SET NULL,
  budget_units          integer,

  attempt_count         integer NOT NULL DEFAULT 0,
  max_attempts          integer NOT NULL DEFAULT 3,

  lease_generation      integer NOT NULL DEFAULT 0,
  lease_id              text,
  worker_id             text REFERENCES workers(id) ON DELETE SET NULL,
  lease_credential_id   text,
  lease_session_ref     text,
  leased_at             text,
  heartbeat_at          text,
  lease_expires_at      text,
  lease_renewals        integer NOT NULL DEFAULT 0,

  checkpoint            text,
  checkpoint_at         text,

  terminal_reason       text,
  last_refusal          text,
  refusal_count         integer NOT NULL DEFAULT 0,

  created_by_type       text NOT NULL,
  created_by_id         text,
  created_at            text NOT NULL,
  updated_at            text NOT NULL,
  ready_at              text,
  completed_at          text,

  CHECK (state IN ('DRAFT','READY','LEASED','COMPLETE','FAILED','NEEDS_HUMAN','CANCELLED')),
  CHECK (priority BETWEEN 0 AND 9),
  CHECK (attempt_count >= 0),
  CHECK (max_attempts >= 1),
  CHECK (lease_generation >= 0),
  CHECK (contract_version >= 1),

  CHECK (
    (state = 'LEASED'
       AND lease_id IS NOT NULL AND worker_id IS NOT NULL AND lease_expires_at IS NOT NULL)
    OR
    (state <> 'LEASED'
       AND lease_id IS NULL AND worker_id IS NULL AND lease_expires_at IS NULL)
  )
);

CREATE INDEX idx_bins_ready ON bins (state, priority DESC, created_at);
CREATE INDEX idx_bins_project ON bins (project_id, state);
CREATE INDEX idx_bins_orchestration ON bins (orchestration_id);

ALTER TABLE work_items ADD COLUMN bin_id text REFERENCES bins(id) ON DELETE SET NULL;
CREATE INDEX idx_work_items_bin ON work_items (bin_id, state);

CREATE TABLE bin_dispatch (
  seq               bigint GENERATED BY DEFAULT AS IDENTITY,
  id                text PRIMARY KEY,
  bin_id            text NOT NULL REFERENCES bins(id) ON DELETE CASCADE,
  lease_generation  integer NOT NULL,

  state             text NOT NULL DEFAULT 'PENDING',

  attempt_count     integer NOT NULL DEFAULT 0,
  max_attempts      integer NOT NULL DEFAULT 5,
  next_attempt_at   text NOT NULL,

  routine_ref       text,
  routine_version   text,
  fire_event_id     text,
  session_ref       text,

  last_error_kind   text,
  last_error        text,

  created_at        text NOT NULL,
  updated_at        text NOT NULL,
  sent_at           text,

  CHECK (state IN ('PENDING','SENDING','SENT','ABANDONED','SUPERSEDED')),
  CHECK (attempt_count >= 0),
  CHECK (max_attempts >= 1)
);

CREATE UNIQUE INDEX idx_bin_dispatch_intent ON bin_dispatch (bin_id, lease_generation);
CREATE INDEX idx_bin_dispatch_pending ON bin_dispatch (state, next_attempt_at);

CREATE TABLE bin_unit_results (
  seq              bigint GENERATED BY DEFAULT AS IDENTITY,
  id               text PRIMARY KEY,
  bin_id           text NOT NULL REFERENCES bins(id) ON DELETE CASCADE,
  unit_key         text NOT NULL,
  work_item_id     text REFERENCES work_items(id) ON DELETE SET NULL,

  value            text NOT NULL,
  content_hash     text NOT NULL,
  lease_id         text,
  lease_generation integer,

  submitted_by     text,
  created_at       text NOT NULL,

  UNIQUE (bin_id, unit_key)
);

-- Append-only, and deliberately without a foreign key to `bins`: an
-- observation a cascade can delete is not an observation.
CREATE TABLE bin_events (
  seq               bigint GENERATED BY DEFAULT AS IDENTITY,
  id                text PRIMARY KEY,
  event_type        text NOT NULL,
  at                text NOT NULL,

  bin_id            text,
  project_id        text,
  layer_id          text,
  orchestration_id  text,
  work_item_id      text,

  worker_id         text,
  session_ref       text,
  routine_ref       text,
  routine_version   text,
  fire_event_id     text,
  provider          text,

  lease_id          text,
  lease_generation  integer,
  attempt           integer,

  duration_ms       integer,
  measures          text NOT NULL DEFAULT '{}',

  outcome           text,
  reason            text,
  is_proxy          integer NOT NULL DEFAULT 0,

  CHECK (is_proxy IN (0, 1))
);

CREATE INDEX idx_bin_events_bin ON bin_events (bin_id, at);
CREATE INDEX idx_bin_events_type ON bin_events (event_type, at);
CREATE INDEX idx_bin_events_session ON bin_events (session_ref);
