-- The Postgres half of migration 026. See that file for the reasoning; this
-- chain is numbered independently and the two versions do not mean the same
-- thing.
--
-- The only deliberate differences are the ones this chain always has: every
-- table carries `seq`, the identity column standing in for SQLite's `rowid`,
-- and booleans are stored as integers so one repository layer reads both
-- backends identically.

CREATE TABLE fleet_accounts (
  seq                  bigint GENERATED BY DEFAULT AS IDENTITY,
  id                   text PRIMARY KEY,
  provider             text NOT NULL DEFAULT 'claude',
  name                 text NOT NULL,
  plan_label           text,
  declared_plan_power  text,

  state                text NOT NULL DEFAULT 'ENABLED',
  state_reason         text,

  retry_at             text,
  last_refusal_at      text,
  last_refusal_reason  text,

  created_at           text NOT NULL,
  updated_at           text NOT NULL,

  UNIQUE (provider, name),
  CHECK (state IN ('ENABLED','DRAINING','UNAVAILABLE','QUARANTINED','RETIRED'))
);

CREATE TABLE fleet_routines (
  seq                  bigint GENERATED BY DEFAULT AS IDENTITY,
  id                   text PRIMARY KEY,
  account_id           text NOT NULL REFERENCES fleet_accounts(id) ON DELETE CASCADE,

  routine_ref          text NOT NULL,
  name                 text NOT NULL,
  routine_version      text,
  base_url             text,

  token_secret_name    text NOT NULL,
  token_digest         text,

  worker_id            text,

  capabilities         text NOT NULL DEFAULT '[]',

  state                text NOT NULL DEFAULT 'ENABLED',
  state_reason         text,

  fire_generation      integer NOT NULL DEFAULT 0,
  consecutive_failures integer NOT NULL DEFAULT 0,
  consecutive_no_shows integer NOT NULL DEFAULT 0,
  total_fires          integer NOT NULL DEFAULT 0,
  total_refusals       integer NOT NULL DEFAULT 0,
  last_fired_at        text,
  last_check_in_at     text,
  retry_at             text,

  created_at           text NOT NULL,
  updated_at           text NOT NULL,

  UNIQUE (routine_ref),
  CHECK (state IN ('ENABLED','DRAINING','UNAVAILABLE','QUARANTINED','RETIRED'))
);

CREATE INDEX idx_fleet_routines_account ON fleet_routines (account_id, state);
CREATE INDEX idx_fleet_routines_eligible ON fleet_routines (state, retry_at);

CREATE TABLE fleet_policy (
  seq                  bigint GENERATED BY DEFAULT AS IDENTITY,
  id                   text PRIMARY KEY,

  scope                text NOT NULL,
  scope_id             text,
  version              integer NOT NULL,

  target               integer NOT NULL,

  auto_scale           integer NOT NULL DEFAULT 0,
  auto_scale_ceiling   integer,
  min_reserve          integer NOT NULL DEFAULT 0,

  boost_target         integer,
  boost_until          text,
  boost_reason         text,

  explore_ceiling      integer,
  explore_until        text,

  paused               integer NOT NULL DEFAULT 0,

  actor                text NOT NULL,
  reason               text NOT NULL,
  created_at           text NOT NULL,

  UNIQUE (scope, scope_id, version),
  CHECK (scope IN ('FLEET','ACCOUNT','ROUTINE')),
  CHECK (target >= 0),
  CHECK (min_reserve >= 0),
  CHECK (paused IN (0,1)),
  CHECK (auto_scale IN (0,1))
);

CREATE INDEX idx_fleet_policy_current ON fleet_policy (scope, scope_id, version DESC);

ALTER TABLE bin_events ADD COLUMN account_id text;
ALTER TABLE bin_events ADD COLUMN routine_id text;
ALTER TABLE bin_events ADD COLUMN evidence_class text;
ALTER TABLE bin_events ADD COLUMN workload_class text;

CREATE INDEX idx_bin_events_account ON bin_events (account_id, at);
CREATE INDEX idx_bin_events_routine ON bin_events (routine_id, at);

ALTER TABLE bin_dispatch ADD COLUMN routine_id text;

ALTER TABLE bins ADD COLUMN required_capabilities text;
ALTER TABLE bins ADD COLUMN workload_class text;

ALTER TABLE research_passes ADD COLUMN executor_worker_id text;
ALTER TABLE research_passes ADD COLUMN executor_routine_id text;
ALTER TABLE research_passes ADD COLUMN executor_account_id text;
ALTER TABLE research_passes ADD COLUMN executor_session_ref text;
