-- The Postgres half of migration 036. See that file for why.
--
-- Every table here carries `seq`, the identity column standing in for SQLite's
-- `rowid`. It is not decoration: `dialect.ts` rewrites `rowid` to `seq` when a
-- statement reaches Postgres, and three of this feature's queries order by it
-- to break ties on an identical timestamp — the delta feed's cursor most of
-- all, where two records sharing a millisecond and no tiebreak is a record a
-- poller can skip. A table created without it fails at the first such query
-- with `column "seq" does not exist`, which is how `012_checkpoint_seq.sql`
-- came to exist and how this comment came to be written.
CREATE TABLE external_records (
  id                   TEXT PRIMARY KEY,
  seq                  bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id           TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  source_system        TEXT NOT NULL,
  source_record_type   TEXT NOT NULL,
  source_record_id     TEXT NOT NULL,
  source_version       TEXT NOT NULL,
  source_created_at    TEXT,
  source_ref           TEXT,
  title                TEXT NOT NULL,
  summary              TEXT NOT NULL,
  attributes           TEXT NOT NULL DEFAULT '{}',
  provenance           TEXT NOT NULL DEFAULT '{}',
  content_hash         TEXT NOT NULL,
  idempotency_key      TEXT NOT NULL,
  candidate_id         TEXT REFERENCES russell_candidates(id) ON DELETE SET NULL,
  commanded_at         TEXT,
  commanded_command    TEXT,
  commanded_by_label   TEXT,
  last_synced_version  TEXT NOT NULL,
  first_seen_at        TEXT NOT NULL,
  updated_at           TEXT NOT NULL,
  UNIQUE (source_system, source_record_id),
  UNIQUE (idempotency_key)
);
CREATE INDEX idx_external_records_project
  ON external_records (project_id, source_system, updated_at);
CREATE INDEX idx_external_records_candidate
  ON external_records (candidate_id);

CREATE TABLE external_record_rejections (
  id                   TEXT PRIMARY KEY,
  seq                  bigint GENERATED BY DEFAULT AS IDENTITY,
  project_id           TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  source_system        TEXT NOT NULL,
  source_record_type   TEXT NOT NULL,
  source_record_id     TEXT NOT NULL DEFAULT '',
  reason               TEXT NOT NULL,
  detail               TEXT NOT NULL,
  first_at             TEXT NOT NULL,
  last_at              TEXT NOT NULL,
  occurrences          INTEGER NOT NULL DEFAULT 1,
  UNIQUE (source_system, source_record_id, reason)
);
CREATE INDEX idx_external_rejections_project
  ON external_record_rejections (project_id, last_at);

CREATE TABLE storage_readings (
  id                TEXT PRIMARY KEY,
  seq               bigint GENERATED BY DEFAULT AS IDENTITY,
  observed_at       TEXT NOT NULL,
  provider          TEXT NOT NULL,
  database_bytes    BIGINT,
  object_bytes      BIGINT,
  object_count      BIGINT,
  object_bytes_raw  BIGINT,
  categories        TEXT NOT NULL DEFAULT '[]'
);
CREATE INDEX idx_storage_readings_at ON storage_readings (observed_at);
