-- The Postgres half of migration 035. See that file for the reasoning; this
-- chain is numbered independently and the two versions do not mean the same
-- thing.
--
-- The only deliberate differences are the ones this chain always has: every
-- table carries `seq`, the identity column standing in for SQLite's `rowid`,
-- serialized JSON and timestamps stay `text`, and booleans are integers — so
-- one repository layer reads both backends identically.
--
-- Generated by transforming the SQLite file rather than retyped, so a column
-- cannot exist in one chain and be forgotten in the other.

/* ------------------------------------------------------------------------- */
/* The contract                                                               */
/* ------------------------------------------------------------------------- */

CREATE TABLE factory_change_requests (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  id                    text PRIMARY KEY,
  project_id            text NOT NULL REFERENCES projects(id),
  -- The logical identity of the ask, supplied by whoever submits it. Two
  -- submissions carrying the same key are the same change request, which is
  -- what makes "submit twice, get one campaign" a property of the schema
  -- rather than of a caller remembering to check first.
  submission_key        text NOT NULL,
  contract_version      integer NOT NULL DEFAULT 1,

  -- What a person supplies.
  objective             text NOT NULL,
  expected_outcome      text NOT NULL,
  non_goals             text NOT NULL DEFAULT '[]',
  acceptance_conditions text NOT NULL DEFAULT '[]',

  -- What Brain derives from the repository and the objective. A person is not
  -- asked to configure any of it.
  repository            text NOT NULL,
  base_branch           text NOT NULL,
  base_sha              text NOT NULL,
  environment           text NOT NULL DEFAULT 'LOCAL',
  risk_class            text NOT NULL DEFAULT 'MEDIUM',
  mutation_scope        text NOT NULL DEFAULT '[]',
  deployment_policy     text NOT NULL DEFAULT 'NONE',
  external_spend_policy text NOT NULL DEFAULT 'PROHIBITED',
  rollback_requirement  text NOT NULL,
  verification_commands text NOT NULL DEFAULT '[]',

  -- Who authorized it. Exactly one of the two is meaningful, and the standing
  -- authority is Russell's own grant rather than a second policy engine.
  approved_by_user_id   text REFERENCES users(id),
  approved_via          text,
  authority_id          text,
  approved_at           text,

  state                 text NOT NULL DEFAULT 'DRAFT',
  created_at            text NOT NULL,
  updated_at            text NOT NULL,

  CHECK (state IN ('DRAFT','APPROVED','WITHDRAWN')),
  CHECK (environment IN ('LOCAL','STAGING','PRODUCTION')),
  CHECK (risk_class IN ('LOW','MEDIUM','HIGH')),
  CHECK (deployment_policy IN ('NONE','STAGING_ONLY','CONTROL_PLANE_AFTER_VERIFICATION')),
  -- The one value this product issues. A paid external effect is not something
  -- a factory may authorize for itself; widening this is a code change.
  CHECK (external_spend_policy IN ('PROHIBITED')),
  CHECK (approved_via IS NULL OR approved_via IN ('PERSON','STANDING_AUTHORITY')),
  CHECK (contract_version >= 1),
  -- An approved change request has an approval. Deny by default, in the schema.
  CHECK (
    (state <> 'APPROVED')
    OR (approved_via IS NOT NULL AND approved_at IS NOT NULL)
  )
);

CREATE UNIQUE INDEX idx_factory_cr_submission
  ON factory_change_requests (project_id, submission_key);
CREATE INDEX idx_factory_cr_project ON factory_change_requests (project_id, state);

CREATE TABLE factory_contract_amendments (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  id                    text PRIMARY KEY,
  change_request_id     text NOT NULL,
  campaign_id           text,
  field                 text NOT NULL,
  old_value             text NOT NULL,
  new_value             text NOT NULL,
  reason                text NOT NULL,
  actor_type            text NOT NULL,
  actor_id              text,
  affected_work         text NOT NULL DEFAULT '[]',
  requires_reverification integer NOT NULL DEFAULT 1,
  from_contract_version integer NOT NULL,
  to_contract_version   integer NOT NULL,
  created_at            text NOT NULL,

  CHECK (actor_type IN ('PERSON','FACTORY')),
  CHECK (requires_reverification IN (0,1))
);

CREATE INDEX idx_factory_amendments_cr
  ON factory_contract_amendments (change_request_id, created_at);

/* ------------------------------------------------------------------------- */
/* The campaign                                                               */
/* ------------------------------------------------------------------------- */

CREATE TABLE factory_campaigns (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  id                  text PRIMARY KEY,
  -- One campaign per change request. The whole of acceptance condition 2.
  change_request_id   text NOT NULL UNIQUE REFERENCES factory_change_requests(id),
  project_id          text NOT NULL REFERENCES projects(id),
  state               text NOT NULL DEFAULT 'PLANNING',
  stage_detail        text,
  base_sha            text NOT NULL,
  integration_branch  text NOT NULL,
  integration_sha     text,
  -- What the scheduler currently believes it should run at once, and why it
  -- believes it. Adaptive, derived from `factory_events`, never configured by
  -- a person.
  lane_target         integer NOT NULL DEFAULT 3,
  lane_target_reason  text NOT NULL DEFAULT 'initial',
  -- An operational fact with an operational remedy, from a closed vocabulary.
  blocker_kind        text,
  blocker_detail      text,
  -- The campaign tick's lease. A second dispatcher that reads generation 7 and
  -- swaps on it loses, exactly like a second worker claiming a unit.
  generation          integer NOT NULL DEFAULT 0,
  lease_owner         text,
  lease_expires_at    text,
  review_rounds       integer NOT NULL DEFAULT 0,
  pr_ref              text,
  pr_url              text,
  started_at          text NOT NULL,
  finished_at         text,
  created_at          text NOT NULL,
  updated_at          text NOT NULL,

  CHECK (state IN (
    'PLANNING','EXECUTING','INTEGRATING','REVIEWING','REPAIRING',
    'VERIFYING','ASSEMBLING','AWAITING_RELEASE','COMPLETE','BLOCKED','CANCELLED'
  )),
  CHECK (lane_target >= 1),
  CHECK (generation >= 0),
  CHECK (review_rounds >= 0),
  CHECK ((lease_owner IS NULL) = (lease_expires_at IS NULL))
);

CREATE INDEX idx_factory_campaigns_project ON factory_campaigns (project_id, state);

/* ------------------------------------------------------------------------- */
/* The work                                                                   */
/* ------------------------------------------------------------------------- */

CREATE TABLE factory_work_units (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  id                text PRIMARY KEY,
  campaign_id       text NOT NULL REFERENCES factory_campaigns(id),
  -- The unit's logical identity. A retry raises `attempt`; it never creates a
  -- second row, so "retries do not create duplicate logical WorkUnits" is a
  -- UNIQUE index rather than a convention.
  unit_key          text NOT NULL,
  kind              text NOT NULL,
  role              text NOT NULL,
  title             text NOT NULL,
  objective         text NOT NULL,
  acceptance        text NOT NULL DEFAULT '[]',
  -- The mutation surface this unit owns. The integrator holds the diff against
  -- it, and the scheduler refuses to lease two units whose surfaces intersect.
  owned_paths       text NOT NULL DEFAULT '[]',
  required_context  text NOT NULL DEFAULT '[]',
  verification      text NOT NULL DEFAULT '[]',
  expected_artifact text NOT NULL DEFAULT '',
  risk              text NOT NULL DEFAULT 'MEDIUM',
  critical_path     integer NOT NULL DEFAULT 0,
  downstream_count  integer NOT NULL DEFAULT 0,
  priority          integer NOT NULL DEFAULT 5,
  model_class       text NOT NULL DEFAULT 'FAST',
  state             text NOT NULL DEFAULT 'BLOCKED',
  attempt           integer NOT NULL DEFAULT 0,
  max_attempts      integer NOT NULL DEFAULT 3,

  lease_generation  integer NOT NULL DEFAULT 0,
  lease_id          text,
  lease_worker_id   text,
  lease_session_id  text,
  leased_at         text,
  lease_expires_at  text,

  worktree_path     text,
  branch            text,
  head_sha          text,
  base_sha          text,

  -- What the worker said, kept as evidence, and never the thing that decides
  -- whether the unit succeeded. The repository decides that.
  worker_summary    text,
  terminal_result   text,
  failure_category  text,
  failure_detail    text,
  -- Rate limiting is backpressure. A deferred unit is not a failed one, so the
  -- deferral lives here and `attempt` is left alone.
  not_before        text,
  repairs_finding_id text,
  created_at        text NOT NULL,
  updated_at        text NOT NULL,

  CHECK (state IN (
    'BLOCKED','READY','LEASED','IMPLEMENTED','INTEGRATED',
    'FAILED','CANCELLED','SUPERSEDED'
  )),
  CHECK (kind IN (
    'INTERFACE','IMPLEMENTATION','TEST','MIGRATION','REPAIR',
    'REVIEW','INTEGRATION','VERIFICATION','DOCS'
  )),
  CHECK (role IN ('ARCHITECT','IMPLEMENTER','REVIEWER','INTEGRATOR','VERIFIER')),
  CHECK (model_class IN ('STRONGEST','FAST')),
  CHECK (risk IN ('LOW','MEDIUM','HIGH')),
  CHECK (attempt >= 0),
  CHECK (max_attempts >= 1),
  CHECK (lease_generation >= 0),
  CHECK (critical_path IN (0,1)),
  -- A lease exists if and only if the unit is LEASED.
  CHECK (
    (state = 'LEASED'
       AND lease_id IS NOT NULL AND lease_worker_id IS NOT NULL
       AND lease_expires_at IS NOT NULL)
    OR
    (state <> 'LEASED'
       AND lease_id IS NULL AND lease_worker_id IS NULL
       AND lease_expires_at IS NULL)
  )
);

CREATE UNIQUE INDEX idx_factory_units_key ON factory_work_units (campaign_id, unit_key);
CREATE INDEX idx_factory_units_state ON factory_work_units (campaign_id, state, priority);
CREATE INDEX idx_factory_units_lease ON factory_work_units (state, lease_expires_at);

CREATE TABLE factory_unit_dependencies (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  campaign_id         text NOT NULL REFERENCES factory_campaigns(id),
  unit_id             text NOT NULL REFERENCES factory_work_units(id),
  depends_on_unit_id  text NOT NULL REFERENCES factory_work_units(id),
  reason              text NOT NULL DEFAULT '',
  created_at          text NOT NULL,
  PRIMARY KEY (unit_id, depends_on_unit_id),
  -- A unit cannot depend on itself. A graph with a self-edge has no order.
  CHECK (unit_id <> depends_on_unit_id)
);

CREATE INDEX idx_factory_deps_campaign ON factory_unit_dependencies (campaign_id);
CREATE INDEX idx_factory_deps_reverse ON factory_unit_dependencies (depends_on_unit_id);

-- A worker's own handover. The point of it is that a *different* worker can
-- resume without reconstructing the investigation, so it is append-only and
-- the newest row for a unit is the one a resuming assignment carries.
CREATE TABLE factory_checkpoints (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  id              text PRIMARY KEY,
  campaign_id     text NOT NULL,
  unit_id         text NOT NULL,
  attempt         integer NOT NULL,
  session_id      text,
  worker_id       text,
  established     text NOT NULL,
  commits         text NOT NULL DEFAULT '[]',
  tests_run       text NOT NULL DEFAULT '[]',
  unresolved      text NOT NULL DEFAULT '',
  next_action     text NOT NULL,
  created_at      text NOT NULL,

  CHECK (attempt >= 0)
);

-- Ordered by insertion, which is `rowid` locally and `seq` in the cloud —
-- `dialect.ts` rewrites the one into the other. Two checkpoints written in the
-- same millisecond would otherwise come back in an arbitrary order, and the
-- newest is the one a resuming assignment carries.
CREATE INDEX idx_factory_checkpoints_unit
  ON factory_checkpoints (unit_id, created_at);

/* ------------------------------------------------------------------------- */
/* The fleet                                                                  */
/* ------------------------------------------------------------------------- */

-- The worker registry. Adding a worker is an INSERT here plus whatever grant
-- its surface needs; it is never a change to factory code. `kind` selects an
-- executor that already exists, and a kind nothing implements is refused at
-- registration rather than discovered at dispatch.
CREATE TABLE factory_workers (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  id                    text PRIMARY KEY,
  name                  text NOT NULL UNIQUE,
  kind                  text NOT NULL,
  -- The account or surface this worker draws its allowance from, by name. An
  -- account is not a worker and a worker is not a Routine: §23's distinction,
  -- kept because sizing a fleet by multiplying a label is sizing it on a
  -- fiction.
  account_ref           text NOT NULL,
  model                 text NOT NULL,
  model_class           text NOT NULL DEFAULT 'FAST',
  capabilities          text NOT NULL DEFAULT '[]',
  repositories          text NOT NULL DEFAULT '[]',
  max_concurrency       integer NOT NULL DEFAULT 1,
  availability          text NOT NULL DEFAULT 'AVAILABLE',
  -- The NAME of the secret, and a digest of the value taken once. Never the
  -- value: a row that held a credential would put it in every projection that
  -- reads the row.
  credential_ref        text,
  credential_digest     text,
  brain_worker_id       text REFERENCES workers(id),
  -- Provider backpressure. Advances on a refusal and leaves the failure streak
  -- alone, because an account at its ceiling is busy rather than broken.
  rate_limited_until    text,
  consecutive_failures  integer NOT NULL DEFAULT 0,
  registered_by_user_id text REFERENCES users(id),
  last_seen_at          text,
  created_at            text NOT NULL,
  updated_at            text NOT NULL,

  CHECK (kind IN ('LOCAL_CLI','COWORK_ROUTINE','REMOTE_SESSION')),
  CHECK (model_class IN ('STRONGEST','FAST','EITHER')),
  CHECK (availability IN ('AVAILABLE','PAUSED','QUARANTINED')),
  CHECK (max_concurrency >= 1),
  CHECK (consecutive_failures >= 0)
);

CREATE INDEX idx_factory_workers_available
  ON factory_workers (availability, rate_limited_until);

-- One execution of one worker. This is the lineage an independence check reads:
-- a review whose session is the session that wrote the code is not a review,
-- and "we could not tell" must never read the same as "we checked".
CREATE TABLE factory_sessions (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  id                  text PRIMARY KEY,
  campaign_id         text NOT NULL,
  unit_id             text,
  worker_id           text NOT NULL,
  account_ref         text NOT NULL,
  attempt             integer NOT NULL DEFAULT 0,
  role                text NOT NULL,
  -- The executor's own identifier for the session it ran. Observed from the
  -- run, never supplied by the worker's output.
  external_session_id text,
  model               text NOT NULL,
  state               text NOT NULL DEFAULT 'RUNNING',
  exit_reason         text,
  duration_ms         integer,
  num_turns           integer,
  -- Token counts and nothing else. No credential, no prompt, no reply.
  usage               text,
  started_at          text NOT NULL,
  ended_at            text,
  created_at          text NOT NULL,
  updated_at          text NOT NULL,

  CHECK (state IN ('RUNNING','FINISHED','FAILED','RATE_LIMITED','ABANDONED')),
  CHECK (role IN ('ARCHITECT','IMPLEMENTER','REVIEWER','INTEGRATOR','VERIFIER')),
  CHECK (attempt >= 0)
);

CREATE INDEX idx_factory_sessions_unit ON factory_sessions (unit_id, started_at);
CREATE INDEX idx_factory_sessions_campaign ON factory_sessions (campaign_id, state);
CREATE INDEX idx_factory_sessions_worker ON factory_sessions (worker_id, state);

/* ------------------------------------------------------------------------- */
/* Judgement                                                                  */
/* ------------------------------------------------------------------------- */

CREATE TABLE factory_reviews (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  id                  text PRIMARY KEY,
  campaign_id         text NOT NULL REFERENCES factory_campaigns(id),
  round               integer NOT NULL DEFAULT 1,
  scope               text NOT NULL DEFAULT 'CAMPAIGN',
  unit_id             text,
  reviewer_session_id text,
  reviewed_sha        text NOT NULL,
  verdict             text NOT NULL,
  summary             text NOT NULL DEFAULT '',
  -- What separation was actually achieved, never rounded up.
  independence        text NOT NULL DEFAULT 'UNKNOWN',
  created_at          text NOT NULL,

  CHECK (scope IN ('CAMPAIGN','UNIT')),
  CHECK (verdict IN ('PASS','CHANGES_REQUIRED','BLOCKED')),
  CHECK (independence IN (
    'UNKNOWN','SESSION_SEPARATED','WORKER_SEPARATED','ACCOUNT_SEPARATED'
  )),
  CHECK (round >= 1)
);

CREATE INDEX idx_factory_reviews_campaign ON factory_reviews (campaign_id, round);

CREATE TABLE factory_findings (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  id                      text PRIMARY KEY,
  review_id               text NOT NULL REFERENCES factory_reviews(id),
  campaign_id             text NOT NULL REFERENCES factory_campaigns(id),
  -- The finding's logical identity inside its review. A re-reported finding
  -- collides rather than queueing a second repair for the same defect.
  finding_key             text NOT NULL,
  severity                text NOT NULL,
  category                text NOT NULL,
  statement               text NOT NULL,
  evidence                text NOT NULL DEFAULT '',
  acceptance_condition_id text,
  state                   text NOT NULL DEFAULT 'OPEN',
  repair_unit_id          text,
  resolution              text,
  created_at              text NOT NULL,
  updated_at              text NOT NULL,

  CHECK (severity IN ('BLOCKER','MAJOR','MINOR')),
  CHECK (state IN ('OPEN','REPAIR_QUEUED','REPAIRED','REJECTED','ACCEPTED_LIMITATION'))
);

CREATE UNIQUE INDEX idx_factory_findings_key
  ON factory_findings (review_id, finding_key);
CREATE INDEX idx_factory_findings_state ON factory_findings (campaign_id, state);

CREATE TABLE factory_integrations (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  id                    text PRIMARY KEY,
  campaign_id           text NOT NULL REFERENCES factory_campaigns(id),
  unit_id               text NOT NULL REFERENCES factory_work_units(id),
  attempt               integer NOT NULL,
  outcome               text NOT NULL,
  reason                text NOT NULL DEFAULT '',
  rejected_paths        text NOT NULL DEFAULT '[]',
  before_sha            text NOT NULL,
  after_sha             text,
  verification          text NOT NULL DEFAULT '[]',
  integrator_session_id text,
  created_at            text NOT NULL,

  CHECK (outcome IN ('MERGED','REJECTED','CONFLICT','DEFERRED','VERIFICATION_FAILED')),
  CHECK (attempt >= 0)
);

CREATE UNIQUE INDEX idx_factory_integrations_attempt
  ON factory_integrations (unit_id, attempt, outcome);
CREATE INDEX idx_factory_integrations_campaign
  ON factory_integrations (campaign_id, created_at);

/* ------------------------------------------------------------------------- */
/* Evidence                                                                   */
/* ------------------------------------------------------------------------- */

-- The capacity and provenance ledger, append-only and without foreign keys: a
-- row a cascade can delete is not a ledger row. Every throughput and
-- concurrency number the factory reports is counted from here, so there is no
-- second table that could drift out of agreement with it.
--
-- `evidence_class` is the honesty requirement. A duration the factory timed is
-- MEASURED; a refusal a provider issued is PROVIDER_ENFORCED; a number
-- computed from other rows is DERIVED; a ceiling nobody has observed is
-- UNKNOWN and stays UNKNOWN.
CREATE TABLE factory_events (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  id             text PRIMARY KEY,
  campaign_id    text,
  unit_id        text,
  worker_id      text,
  session_id     text,
  account_ref    text,
  kind           text NOT NULL,
  phase          text,
  duration_ms    integer,
  evidence_class text NOT NULL DEFAULT 'DERIVED',
  detail         text NOT NULL DEFAULT '{}',
  at             text NOT NULL,

  CHECK (evidence_class IN ('MEASURED','PROVIDER_ENFORCED','DERIVED','UNKNOWN'))
);

CREATE INDEX idx_factory_events_campaign ON factory_events (campaign_id, at);
CREATE INDEX idx_factory_events_kind ON factory_events (kind, at);
CREATE INDEX idx_factory_events_unit ON factory_events (unit_id, at);

-- Large evidence lives in the store; its hash and reference live here. UNIQUE
-- on the hash inside a campaign is the deduplication: the same worker log
-- written twice is one row.
CREATE TABLE factory_artifacts (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  id           text PRIMARY KEY,
  campaign_id  text NOT NULL REFERENCES factory_campaigns(id),
  unit_id      text,
  session_id   text,
  kind         text NOT NULL,
  sha256       text NOT NULL,
  byte_size    integer NOT NULL,
  storage_key  text,
  inline_text  text,
  created_at   text NOT NULL,

  CHECK (kind IN (
    'WORKER_LOG','PATCH','TEST_OUTPUT','BUILD_OUTPUT','REVIEW_INPUT','PR_BODY'
  )),
  CHECK (byte_size >= 0)
);

CREATE UNIQUE INDEX idx_factory_artifacts_dedupe
  ON factory_artifacts (campaign_id, kind, sha256);

-- The human boundary, as a row with a guarded answer. A release a person has
-- not answered is REQUESTED, and nothing about a REQUESTED release lets the
-- factory proceed past it.
CREATE TABLE factory_releases (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  id                 text PRIMARY KEY,
  campaign_id        text NOT NULL REFERENCES factory_campaigns(id),
  kind               text NOT NULL,
  decision           text NOT NULL DEFAULT 'REQUESTED',
  evidence           text NOT NULL DEFAULT '{}',
  decided_by_user_id text REFERENCES users(id),
  decided_reason     text,
  decided_at         text,
  created_at         text NOT NULL,
  updated_at         text NOT NULL,

  CHECK (kind IN ('CONTROL_PLANE','PRODUCT_CHANGE')),
  CHECK (decision IN ('REQUESTED','APPROVED','REFUSED')),
  CHECK ((decision = 'REQUESTED') = (decided_at IS NULL))
);

CREATE INDEX idx_factory_releases_campaign ON factory_releases (campaign_id, decision);
