-- The Postgres half of 040_worker_routing.sql. See that file for the reasoning.
CREATE TABLE worker_routing (
  worker_id    TEXT PRIMARY KEY REFERENCES workers(id) ON DELETE CASCADE,
  families     TEXT NOT NULL,
  repositories TEXT NOT NULL,
  capabilities TEXT NOT NULL,
  reason       TEXT NOT NULL,
  set_by       TEXT NOT NULL,
  created_at   TEXT NOT NULL,
  updated_at   TEXT NOT NULL,
  -- The identity column `dialect.ts` rewrites `rowid` to. Present on every table
  -- here whether or not a query orders by it yet, because the one that does not
  -- have it is the one a later cursor query throws on.
  seq          bigint GENERATED BY DEFAULT AS IDENTITY
);

CREATE INDEX idx_worker_routing_updated ON worker_routing(updated_at);
