-- The Postgres half of migration 049. Same table, same rules; see
-- server/db/migrations/049_project_invitations.sql for the reasoning. The two
-- chains are numbered independently and this is the same change.
--
-- `seq`, the identity column standing in for SQLite's `rowid`, goes in whether
-- or not this table's own queries order by it: `dialect.ts` rewrites `rowid` to
-- `seq`, and a table without one fails every cursor-ordered query on this
-- backend while passing the whole SQLite suite. That has now happened five
-- times.
CREATE TABLE IF NOT EXISTS project_invitations (
  id                  TEXT PRIMARY KEY,
  seq                 bigint GENERATED BY DEFAULT AS IDENTITY,

  project_id          TEXT NOT NULL REFERENCES projects(id),
  invited_email       TEXT NOT NULL,
  role                TEXT NOT NULL CHECK (role IN ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER')),

  token_prefix        TEXT NOT NULL,
  token_digest        TEXT NOT NULL,

  invited_by_user_id  TEXT NOT NULL REFERENCES users(id),

  created_at          TEXT NOT NULL,
  expires_at          TEXT NOT NULL,

  accepted_at         TEXT,
  accepted_user_id    TEXT REFERENCES users(id),

  revoked_at          TEXT,
  revoked_reason      TEXT,

  note                TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_project_invitations_token_prefix
  ON project_invitations (token_prefix);
CREATE INDEX IF NOT EXISTS idx_project_invitations_project ON project_invitations (project_id);
CREATE INDEX IF NOT EXISTS idx_project_invitations_email ON project_invitations (invited_email);
