-- What Brain has established about its own execution capacity, and the bounded
-- experiments it ran to establish it. The SQLite chain's 074, for Postgres.
--
-- The reasoning is written out in full in `migrations/074_capacity_kernel.sql`
-- and is not repeated here. Three differences are Postgres's own and worth
-- naming, because each is a shape this repository has been caught by before:
--
--   * `seq` is a generated identity on both tables. `dialect.ts` rewrites
--     `rowid` to `seq`, so a table without it makes every `ORDER BY … , rowid`
--     throw on the backend production runs while passing the whole SQLite
--     suite. That has now happened three times — `012_checkpoint_seq.sql`,
--     §25's three connect tables, and `worker_sessions` — and the cost each
--     time was a statement that only one dialect could say.
--   * `real` becomes `double precision`, so a fractional throughput figure
--     does not silently lose precision on one backend only.
--   * The partial unique indexes are identical in both dialects, which is the
--     point: the exclusion that stops two current answers to one capacity
--     question is the same statement in both, rather than a constraint one
--     backend enforces and the other does not.

CREATE TABLE capacity_claims (
  seq                   bigint GENERATED BY DEFAULT AS IDENTITY,
  id                    text PRIMARY KEY,

  dimension             text NOT NULL,
  scope                 text NOT NULL,
  scope_id              text,
  workload_class        text NOT NULL DEFAULT 'ANY',

  value                 double precision,
  bound                 text NOT NULL,
  evidence_class        text NOT NULL,
  explanation           text NOT NULL,

  sample_count          integer NOT NULL DEFAULT 0,
  confidence            text NOT NULL,
  evidence_ids          text NOT NULL DEFAULT '[]',
  contradictions        text NOT NULL DEFAULT '[]',
  staleness             text NOT NULL DEFAULT '[]',

  code_version          text,
  config_hash           text,

  first_observed_at     text NOT NULL,
  last_verified_at      text NOT NULL,
  superseded_at         text,
  superseded_by_id      text,
  superseded_reason     text,

  CHECK (bound IN ('AT_LEAST', 'AT_MOST', 'EXACT')),
  CHECK (evidence_class IN ('MEASURED', 'INFERRED', 'UNKNOWN', 'PROVIDER_ENFORCED')),
  CHECK (confidence IN ('LOW', 'MEDIUM', 'HIGH')),
  CHECK (sample_count >= 0),
  CHECK ((evidence_class = 'UNKNOWN') = (value IS NULL))
);

CREATE UNIQUE INDEX idx_capacity_claims_live
  ON capacity_claims (dimension, scope, COALESCE(scope_id, ''), workload_class)
  WHERE superseded_at IS NULL;

CREATE INDEX idx_capacity_claims_scope ON capacity_claims (scope, scope_id, last_verified_at);

CREATE TABLE capacity_experiments (
  seq                     bigint GENERATED BY DEFAULT AS IDENTITY,
  id                      text PRIMARY KEY,

  kind                    text NOT NULL,
  dimension               text NOT NULL,
  scope                   text NOT NULL,
  scope_id                text,
  workload_class          text NOT NULL DEFAULT 'ANY',

  state                   text NOT NULL,

  hypothesis              text NOT NULL,
  success_metric          text NOT NULL,
  stop_condition          text NOT NULL,
  resolves_unknown        text NOT NULL,

  factor                  text,
  baseline_value          double precision,
  canary_value            double precision,

  user_action             text,

  rollback_policy_version integer,
  rollback_target         integer,
  applied_policy_version  integer,

  canary_bin_ids          text NOT NULL DEFAULT '[]',

  baseline_reading        text,
  canary_reading          text,
  verdict                 text,
  verdict_reason          text,

  requested_by            text NOT NULL,
  authority_channel       text NOT NULL DEFAULT 'REPORTED',

  created_at              text NOT NULL,
  updated_at              text NOT NULL,
  canary_until            text,
  settled_at              text,

  CHECK (state IN ('PROPOSED', 'AUTHORIZED', 'CANARY_RUNNING', 'EVALUATING',
                   'ADOPTED', 'ROLLED_BACK', 'ABANDONED', 'NEEDS_USER')),
  CHECK (verdict IS NULL OR verdict IN ('CONFIRMED', 'REFUTED', 'INCONCLUSIVE', 'STOPPED')),
  CHECK (authority_channel IN ('REPORTED', 'SHELL', 'BROWSER')),
  CHECK (state <> 'NEEDS_USER' OR user_action IS NOT NULL),
  CHECK ((state IN ('ADOPTED', 'ROLLED_BACK', 'ABANDONED')) = (verdict IS NOT NULL))
);

CREATE UNIQUE INDEX idx_capacity_experiments_live
  ON capacity_experiments (dimension, scope, COALESCE(scope_id, ''))
  WHERE state IN ('PROPOSED', 'AUTHORIZED', 'CANARY_RUNNING', 'EVALUATING', 'NEEDS_USER');

CREATE INDEX idx_capacity_experiments_state ON capacity_experiments (state, created_at);
