-- PostgreSQL half of 096_fleet_allowance_reports.sql.
CREATE TABLE fleet_allowance_reports (
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  id text PRIMARY KEY,
  account_id text NOT NULL REFERENCES fleet_accounts(id) ON DELETE CASCADE,
  remaining_percent integer NOT NULL CHECK (remaining_percent BETWEEN 0 AND 100),
  reported_at text NOT NULL,
  reported_by text NOT NULL REFERENCES users(id)
);
CREATE INDEX idx_fleet_allowance_reports_latest
  ON fleet_allowance_reports (account_id, reported_at DESC);
