-- PostgreSQL half of 097_factory_line.sql.
CREATE TABLE factory_queue_entries (
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  id text PRIMARY KEY,
  change_request_id text NOT NULL UNIQUE REFERENCES factory_change_requests(id) ON DELETE CASCADE,
  project_id text NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  priority integer NOT NULL,
  state text NOT NULL CHECK (state IN ('QUEUED', 'STARTED', 'WITHDRAWN')),
  queued_by_user_id text NOT NULL REFERENCES users(id),
  queued_at text NOT NULL,
  campaign_id text REFERENCES factory_campaigns(id),
  started_at text,
  withdrawn_at text,
  withdraw_reason text
);
CREATE INDEX idx_factory_queue_next ON factory_queue_entries (state, priority, queued_at);

CREATE TABLE factory_admission_policy (
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  id text PRIMARY KEY,
  max_active integer NOT NULL CHECK (max_active >= 0),
  actor text NOT NULL,
  reason text NOT NULL,
  created_at text NOT NULL
);
CREATE INDEX idx_factory_admission_latest ON factory_admission_policy (created_at DESC);
