-- PostgreSQL half of 098_routine_delivery_proofs.sql.
CREATE TABLE routine_delivery_proofs (
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  id text PRIMARY KEY,
  routine_id text NOT NULL REFERENCES fleet_routines(id) ON DELETE CASCADE,
  repository text NOT NULL,
  bin_id text NOT NULL UNIQUE,
  state text NOT NULL CHECK (state IN ('PENDING', 'PROVEN', 'FAILED')),
  branch text NOT NULL,
  probe_path text NOT NULL,
  head_sha text,
  pull_request integer,
  failure_step text,
  detail text,
  requested_by text NOT NULL,
  created_at text NOT NULL,
  settled_at text
);
CREATE INDEX idx_routine_delivery_proofs_latest
  ON routine_delivery_proofs (routine_id, repository, created_at);
