-- PostgreSQL half of 099_engineering_evidence.sql.
CREATE TABLE engineering_evidence (
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  id text PRIMARY KEY,
  project_id text,
  repository text NOT NULL,
  property_key text NOT NULL,
  status text NOT NULL CHECK (status IN ('PROVEN', 'FAILED', 'STALE', 'UNKNOWN')),
  source_kind text NOT NULL
    CHECK (source_kind IN ('REAL_PRODUCTION', 'CI', 'TEST', 'OPERATOR', 'SYNTHETIC')),
  evidence_ref text NOT NULL,
  code_sha text,
  config_fingerprint text,
  proven_at text NOT NULL,
  valid_until text,
  invalidation_scope text NOT NULL DEFAULT '[]',
  recorded_by_type text NOT NULL CHECK (recorded_by_type IN ('BRAIN', 'WORKER', 'OPERATOR')),
  recorded_by_id text NOT NULL,
  metadata text NOT NULL DEFAULT '{}',
  created_at text NOT NULL
);
CREATE INDEX idx_engineering_evidence_property
  ON engineering_evidence (repository, property_key, created_at);

CREATE TABLE engineering_interventions (
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  id text PRIMARY KEY,
  project_id text,
  task_ref text,
  kind text NOT NULL CHECK (kind IN (
    'OVERENGINEERING_BLOCKED', 'REDUNDANT_TEST_BLOCKED', 'BAD_WAIT_BLOCKED',
    'PREMATURE_STOP_PREVENTED', 'DUPLICATE_MECHANISM_BLOCKED',
    'UNNECESSARY_HUMAN_QUESTION', 'IDLE_WITH_EXECUTABLE_WORK', 'REAL_EVIDENCE_REUSED')),
  rule text NOT NULL,
  attempted_action text NOT NULL,
  replacement_action text NOT NULL,
  minutes_avoided integer,
  actor_type text NOT NULL,
  actor_id text NOT NULL,
  created_at text NOT NULL
);
CREATE INDEX idx_engineering_interventions_kind ON engineering_interventions (kind, created_at);

CREATE TABLE engineering_blockers (
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  id text PRIMARY KEY,
  project_id text,
  task_ref text,
  kind text NOT NULL CHECK (kind IN (
    'AUTO_WAIT', 'RETRYABLE', 'MISSING_AUTHORITY', 'HUMAN_DECISION',
    'EXTERNAL_SERVICE', 'DEFECT', 'AMBIGUOUS_REQUIREMENT')),
  statement text NOT NULL,
  remedy text NOT NULL,
  needs_human integer NOT NULL CHECK (needs_human IN (0, 1)),
  checked text NOT NULL DEFAULT '[]',
  actor_type text NOT NULL,
  actor_id text NOT NULL,
  created_at text NOT NULL
);
