-- A person's standing decision that eligible Factory changes to one repository
-- may be released without them (CLAUDE.md §58, services/factory/release.ts).
-- SQLite chain: 111_factory_release_authorizations.sql.
--
-- The Brain half of a two-key arrangement; the GitHub half is the
-- FACTORY_AUTO_RELEASE variable and the `factory-release` environment. It
-- authorizes nothing services/factory/releaseEligibility.ts calls manual.
-- Revoking keeps the row. One live grant per (project, repository).
CREATE TABLE factory_release_authorizations (
  seq bigint GENERATED BY DEFAULT AS IDENTITY,
  id               TEXT PRIMARY KEY,
  project_id       TEXT NOT NULL REFERENCES projects(id) ON DELETE CASCADE,
  repository_grant TEXT NOT NULL,
  granted_by_id    TEXT NOT NULL,
  authority_channel TEXT NOT NULL CHECK (authority_channel IN ('BROWSER_SESSION', 'SHELL')),
  reason           TEXT NOT NULL,
  expires_at       TEXT NOT NULL,
  created_at       TEXT NOT NULL,
  revoked_at       TEXT,
  revoked_by_id    TEXT,
  revoke_reason    TEXT
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_release_auth_live
  ON factory_release_authorizations (project_id, repository_grant)
  WHERE revoked_at IS NULL;
