/**
 * The generators. Real code that produces a puzzle and its answer together.
 *
 * ---------------------------------------------------------------------------
 * These are the reason the registry can say anything at all
 * ---------------------------------------------------------------------------
 *
 * `FORMAT_MATURITIES` has a `GENERATABLE` rung and no row in this database may
 * claim it. What claims it is a function in this file being registered against
 * a format in `registry.ts`, which is the brief's own requirement — "do not
 * falsely claim support for puzzle formats lacking real validators" — made
 * structural rather than remembered. A format Brain cannot generate simply has
 * no entry, and the reading says so.
 *
 * ---------------------------------------------------------------------------
 * A generator declares nothing about its own quality
 * ---------------------------------------------------------------------------
 *
 * Nothing here returns "this is a valid puzzle" or "this is a medium one".
 * Validity is decided by `validators.ts` running over the payload with no
 * access to what the generator intended, and difficulty is *measured* — for
 * Sudoku by actually solving it with a technique ladder, for the rest by
 * counting a structural property that is named in `basis` rather than dressed
 * up as a calibration. §27's sentence about a factory that could edit its own
 * acceptance conditions is the same rule: a generator that graded itself would
 * be grading its own exam.
 *
 * **What none of these has is a difficulty calibrated against real solve
 * times.** That needs human playtest data this Brain does not hold, and the
 * honest consequence is that `difficulty_basis` names the structural thing
 * actually counted and the reading reports calibration as an open gap rather
 * than implying one.
 */
import { prngFor, type Prng } from './prng.ts';
import { canonicalGrid, gridFromRows } from './grid.ts';
import { refuse, type GeneratorOutcome } from './kinds.ts';

/* ==========================================================================
 * Shared spec reading
 *
 * A generator validates its own spec and refuses with a sentence naming what
 * was wrong. Nothing coerces: a width of "nine" is refused rather than
 * silently becoming 0, because a generator that quietly produced a degenerate
 * puzzle is the truncation failure one layer down.
 * ======================================================================== */

function intField(
  spec: Record<string, unknown>,
  key: string,
  fallback: number | null,
  bounds: { min: number; max: number },
): number | string {
  const raw = spec[key];
  if (raw === undefined || raw === null) {
    if (fallback === null) return `${key} is required and must be a whole number.`;
    return fallback;
  }
  if (typeof raw !== 'number' || !Number.isInteger(raw)) {
    return `${key} must be a whole number, not ${JSON.stringify(raw)}.`;
  }
  if (raw < bounds.min || raw > bounds.max) {
    return `${key} must be between ${bounds.min} and ${bounds.max}; it was ${raw}.`;
  }
  return raw;
}

function stringListField(spec: Record<string, unknown>, key: string): string[] | string {
  const raw = spec[key];
  if (raw === undefined || raw === null) return [];
  if (!Array.isArray(raw)) return `${key} must be a list of strings.`;
  const out: string[] = [];
  for (const entry of raw) {
    if (typeof entry !== 'string') return `${key} must contain only strings.`;
    const tidy = entry.trim();
    if (tidy) out.push(tidy);
  }
  return out;
}

/* ==========================================================================
 * SUDOKU
 *
 * Generated by filling a complete grid and then removing clues only while a
 * *counting* solver still finds exactly one solution. Uniqueness is therefore
 * a property of how the puzzle was made rather than something hoped for
 * afterwards — and `validators.ts` proves it again independently, because a
 * generator's own account of itself is never the evidence.
 * ======================================================================== */

const SUDOKU_UNITS = (() => {
  const units: number[][] = [];
  for (let r = 0; r < 9; r += 1) units.push([...Array(9)].map((_, c) => r * 9 + c));
  for (let c = 0; c < 9; c += 1) units.push([...Array(9)].map((_, r) => r * 9 + c));
  for (let br = 0; br < 3; br += 1) {
    for (let bc = 0; bc < 3; bc += 1) {
      const cells: number[] = [];
      for (let r = 0; r < 3; r += 1) {
        for (let c = 0; c < 3; c += 1) cells.push((br * 3 + r) * 9 + (bc * 3 + c));
      }
      units.push(cells);
    }
  }
  return units;
})();

/** Which units each cell belongs to, precomputed — the inner loop of everything below. */
const SUDOKU_PEERS = (() => {
  const peers: number[][] = [];
  for (let cell = 0; cell < 81; cell += 1) {
    const set = new Set<number>();
    for (const unit of SUDOKU_UNITS) {
      if (!unit.includes(cell)) continue;
      for (const other of unit) if (other !== cell) set.add(other);
    }
    peers.push([...set]);
  }
  return peers;
})();

export function sudokuAllows(grid: readonly number[], cell: number, value: number): boolean {
  const peers = SUDOKU_PEERS[cell];
  if (!peers) return false;
  for (const peer of peers) {
    if (grid[peer] === value) return false;
  }
  return true;
}

/** Fill an empty grid completely, in a shuffled order so the result varies with the seed. */
function fillGrid(grid: number[], rng: Prng): boolean {
  const cell = grid.indexOf(0);
  if (cell === -1) return true;
  for (const value of rng.shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9])) {
    if (!sudokuAllows(grid, cell, value)) continue;
    grid[cell] = value;
    if (fillGrid(grid, rng)) return true;
    grid[cell] = 0;
  }
  return false;
}

/**
 * How many solutions this grid has, counted no further than `limit`.
 *
 * Stopping at the limit is what makes uniqueness cheap to establish: the only
 * question ever asked is "is there more than one", and counting all of them
 * for a nearly-empty grid would take longer than anybody would wait.
 */
export function sudokuSolutionCount(grid: readonly number[], limit: number): number {
  const work = grid.slice();
  const walk = (): number => {
    // Most-constrained cell first. Without it a sparse grid takes minutes; with
    // it, milliseconds — and it changes nothing about the answer.
    let best = -1;
    let bestOptions: number[] = [];
    for (let cell = 0; cell < 81; cell += 1) {
      if (work[cell] !== 0) continue;
      const options: number[] = [];
      for (let value = 1; value <= 9; value += 1) {
        if (sudokuAllows(work, cell, value)) options.push(value);
      }
      if (options.length === 0) return 0;
      if (best === -1 || options.length < bestOptions.length) {
        best = cell;
        bestOptions = options;
        if (options.length === 1) break;
      }
    }
    if (best === -1) return 1;

    let found = 0;
    for (const value of bestOptions) {
      work[best] = value;
      found += walk();
      work[best] = 0;
      if (found >= limit) break;
    }
    return found;
  };
  return walk();
}

/**
 * What a solver actually needed, by climbing a ladder of techniques.
 *
 * 1  every step was a naked single — one candidate left in a cell.
 * 2  at least one step needed a hidden single — one place left in a unit.
 * 3  neither was ever enough, so the puzzle requires search.
 *
 * This is a *measurement of the puzzle*, not a label chosen by the generator,
 * and `difficulty_basis` says exactly that. It is deliberately not called a
 * calibration: mapping a rung onto how long a person takes needs playtest data
 * nothing here holds.
 */
export function sudokuTechniqueRung(givens: readonly number[]): number {
  const work = givens.slice();
  let rung = 1;

  for (;;) {
    if (!work.includes(0)) return rung;

    let placed = false;

    // Naked singles.
    for (let cell = 0; cell < 81 && !placed; cell += 1) {
      if (work[cell] !== 0) continue;
      let only = 0;
      let count = 0;
      for (let value = 1; value <= 9; value += 1) {
        if (!sudokuAllows(work, cell, value)) continue;
        count += 1;
        only = value;
        if (count > 1) break;
      }
      if (count === 1) {
        work[cell] = only;
        placed = true;
      }
    }
    if (placed) continue;

    // Hidden singles.
    for (const unit of SUDOKU_UNITS) {
      for (let value = 1; value <= 9 && !placed; value += 1) {
        let target = -1;
        let count = 0;
        for (const cell of unit) {
          if (work[cell] !== 0) continue;
          if (!sudokuAllows(work, cell, value)) continue;
          count += 1;
          target = cell;
          if (count > 1) break;
        }
        if (count === 1 && target >= 0) {
          work[target] = value;
          rung = Math.max(rung, 2);
          placed = true;
        }
      }
      if (placed) break;
    }
    if (placed) continue;

    return 3;
  }
}

const BLANK = '.';

export function generateSudoku(input: {
  spec: Record<string, unknown>;
  seed: string;
}): GeneratorOutcome {
  const targetGivens = intField(input.spec, 'givens', 30, { min: 17, max: 80 });
  if (typeof targetGivens === 'string') return refuse(targetGivens);

  const symmetric = input.spec['symmetric'];
  if (symmetric !== undefined && typeof symmetric !== 'boolean') {
    return refuse('symmetric must be true or false.');
  }
  const useSymmetry = symmetric !== false;

  const rng = prngFor(input.seed);
  const solution = new Array<number>(81).fill(0);
  if (!fillGrid(solution, rng)) {
    return refuse('No complete grid could be built from this seed.');
  }

  const puzzle = solution.slice();
  let remaining = 81;

  /*
   * Remove a clue only while exactly one solution survives.
   *
   * With symmetry on, the cell and its 180-degree partner go together — the
   * convention a printed Sudoku follows — and both are restored if the pair
   * costs uniqueness. Removing them one at a time would produce grids that
   * look wrong on a page for no gain.
   */
  for (const cell of rng.shuffle([...Array(81)].map((_, index) => index))) {
    if (remaining <= targetGivens) break;
    const partner = 80 - cell;
    const group = useSymmetry && partner !== cell ? [cell, partner] : [cell];
    if (group.some((one) => puzzle[one] === 0)) continue;
    if (remaining - group.length < targetGivens) continue;

    const saved = group.map((one) => puzzle[one] ?? 0);
    for (const one of group) puzzle[one] = 0;

    if (sudokuSolutionCount(puzzle, 2) === 1) {
      remaining -= group.length;
    } else {
      group.forEach((one, index) => {
        puzzle[one] = saved[index] ?? 0;
      });
    }
  }

  const givensText = puzzle.map((value) => (value === 0 ? BLANK : String(value))).join('');
  const solutionText = solution.join('');

  const rows: string[] = [];
  for (let row = 0; row < 9; row += 1) rows.push(givensText.slice(row * 9, row * 9 + 9));

  return {
    ok: true,
    value: {
      payload: {
        kind: 'SUDOKU',
        size: 9,
        box: { width: 3, height: 3 },
        givens: givensText,
        solution: solutionText,
        givenCount: remaining,
      },
      /*
       * Relabelled and folded over the eight symmetries, so the same grid
       * rotated or with its digits renamed collides. Band and stack
       * permutations are not caught; `grid.ts` says so and says why the miss
       * is the safe direction.
       */
      canonical: canonicalGrid(gridFromRows(rows), { blanks: new Set([BLANK]) }),
      difficulty: {
        value: sudokuTechniqueRung(puzzle),
        basis:
          'TECHNIQUE_RUNG: 1 naked singles only, 2 needs a hidden single, 3 needs search. ' +
          'Measured by solving it; not calibrated against human solve times.',
      },
    },
  };
}

/* ==========================================================================
 * WORD SEARCH
 *
 * The interesting part is not the placement; it is what happens afterwards.
 * A filled grid routinely contains a listed word somewhere nobody put it,
 * which makes the answer key wrong, and it can contain a string nobody wants
 * printed. Both are checked here and both are checked again, independently,
 * by the validator.
 * ======================================================================== */

const DIRECTIONS: { dr: number; dc: number; diagonal: boolean; reverse: boolean }[] = [
  { dr: 0, dc: 1, diagonal: false, reverse: false },
  { dr: 1, dc: 0, diagonal: false, reverse: false },
  { dr: 0, dc: -1, diagonal: false, reverse: true },
  { dr: -1, dc: 0, diagonal: false, reverse: true },
  { dr: 1, dc: 1, diagonal: true, reverse: false },
  { dr: 1, dc: -1, diagonal: true, reverse: true },
  { dr: -1, dc: 1, diagonal: true, reverse: true },
  { dr: -1, dc: -1, diagonal: true, reverse: true },
];

const LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ';

/** Every maximal straight line through the grid, in all eight directions. */
export function wordSearchLines(rows: readonly string[]): string[] {
  const height = rows.length;
  const width = height > 0 ? (rows[0]?.length ?? 0) : 0;
  const lines: string[] = [];

  const walk = (r0: number, c0: number, dr: number, dc: number) => {
    let out = '';
    let r = r0;
    let c = c0;
    while (r >= 0 && c >= 0 && r < height && c < width) {
      out += rows[r]?.[c] ?? '';
      r += dr;
      c += dc;
    }
    if (out.length > 1) lines.push(out);
  };

  for (let r = 0; r < height; r += 1) walk(r, 0, 0, 1);
  for (let c = 0; c < width; c += 1) walk(0, c, 1, 0);
  for (let r = 0; r < height; r += 1) walk(r, 0, 1, 1);
  for (let c = 1; c < width; c += 1) walk(0, c, 1, 1);
  for (let r = 0; r < height; r += 1) walk(r, width - 1, 1, -1);
  for (let c = width - 2; c >= 0; c -= 1) walk(0, c, 1, -1);

  // Both readings of every line, so a backwards word is found the same way.
  return lines.flatMap((line) => [line, [...line].reverse().join('')]);
}

export function countOccurrences(rows: readonly string[], needle: string): number {
  if (!needle) return 0;
  let total = 0;
  for (const line of wordSearchLines(rows)) {
    let from = 0;
    for (;;) {
      const at = line.indexOf(needle, from);
      if (at === -1) break;
      total += 1;
      from = at + 1;
    }
  }
  return total;
}

export function generateWordSearch(input: {
  spec: Record<string, unknown>;
  seed: string;
}): GeneratorOutcome {
  const width = intField(input.spec, 'width', 12, { min: 4, max: 40 });
  if (typeof width === 'string') return refuse(width);
  const height = intField(input.spec, 'height', 12, { min: 4, max: 40 });
  if (typeof height === 'string') return refuse(height);

  const wordsRaw = stringListField(input.spec, 'words');
  if (typeof wordsRaw === 'string') return refuse(wordsRaw);
  const words = [...new Set(wordsRaw.map((word) => word.toUpperCase().replace(/[^A-Z]/g, '')))]
    .filter((word) => word.length >= 3)
    .sort((a, b) => b.length - a.length);
  if (words.length === 0) {
    return refuse('words must contain at least one entry of three letters or more.');
  }

  const prohibitedRaw = stringListField(input.spec, 'prohibited');
  if (typeof prohibitedRaw === 'string') return refuse(prohibitedRaw);
  const prohibited = [
    ...new Set(prohibitedRaw.map((one) => one.toUpperCase().replace(/[^A-Z]/g, ''))),
  ].filter((one) => one.length >= 3);

  const allowDiagonal = input.spec['allowDiagonal'] !== false;
  const allowReverse = input.spec['allowReverse'] !== false;
  const directions = DIRECTIONS.filter(
    (one) => (allowDiagonal || !one.diagonal) && (allowReverse || !one.reverse),
  );

  const longest = words[0]?.length ?? 0;
  if (longest > Math.max(width, height)) {
    return refuse(
      `"${words[0]}" is ${longest} letters and the grid is ${width}x${height}. Widen the grid ` +
        'or shorten the list; a word that cannot fit is refused rather than dropped.',
    );
  }

  const rng = prngFor(input.seed);

  /*
   * Placement and fill are retried together.
   *
   * The fill is what creates an accidental occurrence, so a grid refused for
   * one is re-filled rather than re-placed — but a placement can also make the
   * problem unavoidable, so the whole thing is retried a bounded number of
   * times and then refused honestly. A generator that returned the grid
   * anyway would be handing over a wrong answer key.
   */
  const ATTEMPTS = 40;
  for (let attempt = 0; attempt < ATTEMPTS; attempt += 1) {
    const cells = new Array<string>(width * height).fill('');
    const placements: { word: string; row: number; col: number; dr: number; dc: number }[] = [];

    let placedAll = true;
    for (const word of words) {
      let placed = false;
      for (let tries = 0; tries < 400 && !placed; tries += 1) {
        const dir = rng.pick(directions);
        if (!dir) break;
        const row = rng.int(height);
        const col = rng.int(width);
        const endRow = row + dir.dr * (word.length - 1);
        const endCol = col + dir.dc * (word.length - 1);
        if (endRow < 0 || endCol < 0 || endRow >= height || endCol >= width) continue;

        let fits = true;
        for (let index = 0; index < word.length && fits; index += 1) {
          const at = (row + dir.dr * index) * width + (col + dir.dc * index);
          const existing = cells[at] ?? '';
          if (existing !== '' && existing !== word[index]) fits = false;
        }
        if (!fits) continue;

        for (let index = 0; index < word.length; index += 1) {
          const at = (row + dir.dr * index) * width + (col + dir.dc * index);
          cells[at] = word[index] ?? '';
        }
        placements.push({ word, row, col, dr: dir.dr, dc: dir.dc });
        placed = true;
      }
      if (!placed) {
        placedAll = false;
        break;
      }
    }
    if (!placedAll) continue;

    for (let index = 0; index < cells.length; index += 1) {
      if (cells[index] === '') cells[index] = LETTERS[rng.int(26)] ?? 'A';
    }

    const rows: string[] = [];
    for (let row = 0; row < height; row += 1) {
      rows.push(cells.slice(row * width, (row + 1) * width).join(''));
    }

    // Every listed word must appear exactly once, or the answer key is a lie.
    const ambiguous = words.find((word) => countOccurrences(rows, word) !== 1);
    if (ambiguous) continue;

    const offending = prohibited.find((one) => countOccurrences(rows, one) > 0);
    if (offending) continue;

    return {
      ok: true,
      value: {
        payload: {
          kind: 'WORD_SEARCH',
          width,
          height,
          rows,
          words,
          placements,
          /*
           * Carried on the payload rather than left in the spec, because the
           * validator is given the payload and nothing else. A check that had
           * to ask the generator what it was screening against would be
           * checking the intention instead of the artifact.
           */
          prohibited,
        },
        canonical: `${canonicalGrid(gridFromRows(rows))}|${[...words].sort().join(',')}`,
        difficulty: {
          value: Math.min(
            5,
            1 +
              Math.round(
                (placements.filter((one) => one.dr !== 0 && one.dc !== 0).length / words.length) *
                  2 +
                  (placements.filter((one) => one.dr < 0 || one.dc < 0).length / words.length) * 2,
              ),
          ),
          basis:
            'DIRECTION_MIX: how many words run diagonally and how many run backwards. A ' +
            'structural count of the grid, not a calibration against solve times.',
        },
      },
    };
  }

  return refuse(
    `No ${width}x${height} grid could hold these ${words.length} word(s) exactly once each ` +
      `without producing a screened string, in ${ATTEMPTS} attempts. Widen the grid, shorten ` +
      'the list, or allow more directions.',
  );
}

/* ==========================================================================
 * MAZE
 *
 * A randomized depth-first carve produces a spanning tree of the cells, and a
 * spanning tree has exactly one simple path between any two cells. So
 * uniqueness is structural here rather than searched for — and the validator
 * proves the structure independently by counting edges and walking the graph,
 * instead of taking the generator's word for it.
 * ======================================================================== */

const NORTH = 1;
const EAST = 2;
const SOUTH = 4;
const WEST = 8;

const STEPS: { bit: number; opposite: number; dr: number; dc: number }[] = [
  { bit: NORTH, opposite: SOUTH, dr: -1, dc: 0 },
  { bit: EAST, opposite: WEST, dr: 0, dc: 1 },
  { bit: SOUTH, opposite: NORTH, dr: 1, dc: 0 },
  { bit: WEST, opposite: EAST, dr: 0, dc: -1 },
];

export function mazeNeighbours(
  passages: readonly number[],
  width: number,
  height: number,
  cell: number,
): number[] {
  const out: number[] = [];
  const row = Math.floor(cell / width);
  const col = cell % width;
  const open = passages[cell] ?? 0;
  for (const step of STEPS) {
    if ((open & step.bit) === 0) continue;
    const r = row + step.dr;
    const c = col + step.dc;
    if (r < 0 || c < 0 || r >= height || c >= width) continue;
    out.push(r * width + c);
  }
  return out;
}

export function generateMaze(input: {
  spec: Record<string, unknown>;
  seed: string;
}): GeneratorOutcome {
  const width = intField(input.spec, 'width', 15, { min: 3, max: 60 });
  if (typeof width === 'string') return refuse(width);
  const height = intField(input.spec, 'height', 15, { min: 3, max: 60 });
  if (typeof height === 'string') return refuse(height);

  const rng = prngFor(input.seed);
  const total = width * height;
  const passages = new Array<number>(total).fill(0);
  const seen = new Array<boolean>(total).fill(false);

  // Iterative, because a 60x60 maze carved recursively can exhaust the stack —
  // and a generator that threw would be a crash rather than a refusal.
  const stack: number[] = [0];
  seen[0] = true;
  let visited = 1;

  while (stack.length > 0) {
    const cell = stack[stack.length - 1];
    if (cell === undefined) break;
    const row = Math.floor(cell / width);
    const col = cell % width;

    const options = rng.shuffle(STEPS).filter((step) => {
      const r = row + step.dr;
      const c = col + step.dc;
      if (r < 0 || c < 0 || r >= height || c >= width) return false;
      return !seen[r * width + c];
    });

    const step = options[0];
    if (!step) {
      stack.pop();
      continue;
    }

    const next = (row + step.dr) * width + (col + step.dc);
    passages[cell] = (passages[cell] ?? 0) | step.bit;
    passages[next] = (passages[next] ?? 0) | step.opposite;
    seen[next] = true;
    visited += 1;
    stack.push(next);
  }

  if (visited !== total) {
    return refuse(`The carve reached ${visited} of ${total} cells, so the maze is not connected.`);
  }

  const start = 0;
  const end = total - 1;

  // The one simple path, found by walking the tree.
  const cameFrom = new Array<number>(total).fill(-1);
  const queue: number[] = [start];
  const reached = new Array<boolean>(total).fill(false);
  reached[start] = true;
  while (queue.length > 0) {
    const cell = queue.shift();
    if (cell === undefined) break;
    for (const next of mazeNeighbours(passages, width, height, cell)) {
      if (reached[next]) continue;
      reached[next] = true;
      cameFrom[next] = cell;
      queue.push(next);
    }
  }
  if (!reached[end]) return refuse('No path from the start to the end was produced.');

  const path: number[] = [];
  for (let cell = end; cell !== -1; cell = cameFrom[cell] ?? -1) {
    path.push(cell);
    if (cell === start) break;
  }
  path.reverse();

  const deadEnds = passages.filter((open) => {
    let count = 0;
    for (const step of STEPS) if ((open & step.bit) !== 0) count += 1;
    return count === 1;
  }).length;

  const rows: string[] = [];
  for (let row = 0; row < height; row += 1) {
    rows.push(
      passages
        .slice(row * width, (row + 1) * width)
        .map((open) => open.toString(16))
        .join(''),
    );
  }

  return {
    ok: true,
    value: {
      payload: {
        kind: 'MAZE',
        width,
        height,
        /** One hex digit per cell: which of N=1 E=2 S=4 W=8 are open. */
        passages: rows,
        start,
        end,
        solution: path,
      },
      canonical: canonicalGrid(gridFromRows(rows)),
      difficulty: {
        value: Math.min(
          5,
          1 + Math.round((path.length / total) * 4 + (deadEnds / total) * 4),
        ),
        basis:
          'PATH_AND_DEAD_ENDS: how much of the maze the solution crosses and how many dead ' +
          'ends it offers. A structural count, not a calibration against solve times.',
      },
    },
  };
}

/* ==========================================================================
 * CRYPTOGRAM
 *
 * The only format here whose content is not generated but *supplied*, which
 * makes it the one where rights are a live question on every instance rather
 * than a property of a lexicon. A master whose text is somebody's copyrighted
 * quotation is exactly what `rights_basis` exists to stop reaching an edition,
 * and nothing in this function can tell the difference — which is why the
 * check lives on the master and is made by a person.
 * ======================================================================== */

export function generateCryptogram(input: {
  spec: Record<string, unknown>;
  seed: string;
}): GeneratorOutcome {
  const raw = input.spec['text'];
  if (typeof raw !== 'string' || !raw.trim()) {
    return refuse('text is required and must be the phrase to encipher.');
  }
  const plaintext = raw.replace(/\s+/g, ' ').trim().toUpperCase();

  const attributionRaw = input.spec['attribution'];
  if (attributionRaw !== undefined && typeof attributionRaw !== 'string') {
    return refuse('attribution must be a string when it is given.');
  }
  const attribution = typeof attributionRaw === 'string' ? attributionRaw.trim() : null;

  const used = new Set([...plaintext].filter((ch) => ch >= 'A' && ch <= 'Z'));
  if (used.size < 5) {
    return refuse(
      `A cryptogram needs at least five distinct letters to be solvable by frequency; this ` +
        `text has ${used.size}.`,
    );
  }

  const rng = prngFor(input.seed);
  const alphabet = [...LETTERS];

  /*
   * A derangement: no letter may stand for itself.
   *
   * Shuffling until nothing is fixed is the straightforward way and it
   * terminates quickly — roughly 1 in e of all permutations is a derangement,
   * so the expected number of shuffles is under three. It is bounded anyway,
   * because an unbounded loop in a generator is a hang rather than a refusal.
   */
  let cipher: string[] | null = null;
  for (let attempt = 0; attempt < 200; attempt += 1) {
    const candidate = rng.shuffle(alphabet);
    if (candidate.every((letter, index) => letter !== alphabet[index])) {
      cipher = candidate;
      break;
    }
  }
  if (!cipher) return refuse('No substitution without a fixed point was found for this seed.');

  const key: Record<string, string> = {};
  alphabet.forEach((letter, index) => {
    key[letter] = cipher[index] ?? letter;
  });

  const ciphertext = [...plaintext]
    .map((ch) => (ch >= 'A' && ch <= 'Z' ? (key[ch] ?? ch) : ch))
    .join('');

  return {
    ok: true,
    value: {
      payload: {
        kind: 'CRYPTOGRAM',
        plaintext,
        ciphertext,
        key,
        attribution,
      },
      /*
       * The canonical form is the *plaintext*, deliberately.
       *
       * Two cryptograms of one quotation under two substitutions are the same
       * puzzle to a buyer who has solved either, so treating them as distinct
       * would let the multiplier be inflated by re-enciphering. That is the
       * anti-reskin rule arriving one level below the edition.
       */
      canonical: `CRYPTOGRAM:${plaintext.replace(/[^A-Z]/g, '')}`,
      difficulty: {
        value: Math.min(5, Math.max(1, 6 - Math.floor(plaintext.length / 25))),
        basis:
          'LENGTH_AND_LETTER_COVERAGE: a longer text with more distinct letters gives more for ' +
          'frequency analysis to work on. A structural count, not a calibration against solve ' +
          'times.',
      },
    },
  };
}
