/**
 * Working out which layer a passage is about, from the passage.
 *
 * A filename is a hint. It is the weakest evidence there is — it was typed by a
 * person in a hurry, or generated by an export, and it says nothing about what is
 * inside. `conversation_transcript_best_effort.txt` is the whole argument: a
 * name that carries no layer, no version and no subject, over a file that
 * contains all three many times over.
 *
 * So classification here reads the text. The vocabulary it matches against is
 * the project's own audit profile — each layer already declares what it owns,
 * what it must not own, and what an auditor checks it for, and that is a better
 * description of the layer's subject than anything invented separately. The
 * profile stays the single place per-project criteria live.
 *
 * Every result carries a confidence and a rationale, and nothing it produces is
 * evidence until a person accepts it. A transcript is a record of thinking, not
 * a set of audited artifacts.
 *
 * The text being classified is untrusted. This module matches patterns against
 * it and never follows anything written in it.
 */
import type { Layer } from '../../domain/types.ts';
import { getAuditProfile, getLayerCriteria, type AuditProfile } from '../../domain/auditProfile.ts';
import { VERSION_RE_SOURCE } from '../../domain/version.ts';

export type LinkType = 'REFERENCE' | 'RESEARCH_INPUT' | 'COMPLETED_ARTIFACT';

export interface LayerProposal {
  layerId: string;
  layerName: string;
  version: string | null;
  linkType: LinkType;
  confidence: number;
  rationale: string;
}

/** Words too common to mean anything when matching a subject. */
const STOP = new Set([
  'the', 'and', 'for', 'that', 'this', 'with', 'from', 'what', 'which', 'their', 'they',
  'have', 'has', 'are', 'was', 'were', 'been', 'its', 'how', 'why', 'when', 'who', 'must',
  'not', 'can', 'will', 'would', 'should', 'could', 'about', 'into', 'than', 'then', 'them',
  'exist', 'exists', 'work', 'works', 'layer', 'logic', 'model', 'rules', 'each', 'every',
]);

function terms(text: string): string[] {
  return [
    ...new Set(
      text
        .toLowerCase()
        .split(/[^a-z0-9]+/)
        .filter((word) => word.length > 3 && !STOP.has(word)),
    ),
  ];
}

/** Version mentions in the passage, e.g. "World Model v1B" or "v3.1". */
function versionsIn(text: string): string[] {
  const found = new Set<string>();
  const pattern = new RegExp(`\\b${VERSION_RE_SOURCE}\\b`, 'gi');
  let match = pattern.exec(text);
  while (match !== null) {
    found.add(match[0].trim());
    match = pattern.exec(text);
  }
  return [...found];
}

interface LayerVocabulary {
  layer: Layer;
  /** Distinctive words from the layer's name. */
  nameTerms: string[];
  /** Distinctive words from what the profile says the layer owns. */
  subjectTerms: string[];
}

function buildVocabulary(layers: Layer[], profile: AuditProfile | null): LayerVocabulary[] {
  return layers.map((layer) => {
    const criteria = profile ? getLayerCriteria(profile, layer.slug) : null;
    const subject = criteria ? `${criteria.owns} ${criteria.auditFor.join(' ')}` : '';
    return {
      layer,
      nameTerms: terms(layer.name),
      subjectTerms: terms(subject),
    };
  });
}

/** Count how many times any of `needles` appears in the lowered text. */
function countHits(lowered: string, needles: string[]): { matched: string[]; count: number } {
  const matched: string[] = [];
  let count = 0;
  for (const needle of needles) {
    // Word-boundary match, so "custody" does not fire on "custodian's".
    const pattern = new RegExp(`\\b${needle.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}`, 'g');
    const hits = lowered.match(pattern);
    if (hits && hits.length > 0) {
      matched.push(needle);
      count += hits.length;
    }
  }
  return { matched, count };
}

export interface ClassifyInput {
  text: string;
  layers: Layer[];
  projectSlug: string;
  /** What kind of passage this is; it changes what a link to a layer means. */
  segmentType?: string;
  /** Only propose links at or above this confidence. */
  minConfidence?: number;
  /** At most this many layers per passage; a passage about everything is about nothing. */
  maxProposals?: number;
}

/**
 * Propose the layers a passage belongs to.
 *
 * A passage may legitimately touch several — that is the whole reason a
 * transcript cannot be filed under one — so this returns a ranked list rather
 * than a single answer.
 */
export function classifyToLayers(input: ClassifyInput): LayerProposal[] {
  const profile = getAuditProfile(input.projectSlug);
  const vocabulary = buildVocabulary(input.layers, profile);
  const lowered = input.text.toLowerCase();
  const minConfidence = input.minConfidence ?? 0.3;
  const maxProposals = input.maxProposals ?? 3;
  const mentionedVersions = versionsIn(input.text);

  const scored = vocabulary.map((entry) => {
    // The layer named outright is far stronger evidence than its subject matter,
    // which any neighbouring layer might also discuss.
    const namedOutright = lowered.includes(entry.layer.name.toLowerCase());
    const name = countHits(lowered, entry.nameTerms);
    const subject = countHits(lowered, entry.subjectTerms);

    const nameShare = entry.nameTerms.length === 0 ? 0 : name.matched.length / entry.nameTerms.length;
    const subjectShare =
      entry.subjectTerms.length === 0 ? 0 : subject.matched.length / entry.subjectTerms.length;

    const score =
      (namedOutright ? 0.55 : 0) + nameShare * 0.25 + Math.min(1, subjectShare * 2.5) * 0.3;

    return { entry, namedOutright, name, subject, subjectShare, score };
  });

  scored.sort((a, b) => b.score - a.score);

  const proposals: LayerProposal[] = [];
  for (const candidate of scored) {
    if (proposals.length >= maxProposals) break;
    const confidence = Number(Math.min(0.95, candidate.score).toFixed(2));
    if (confidence < minConfidence) continue;

    const layerName = candidate.entry.layer.name;
    // A version stated next to the layer's own name belongs to it; a version
    // floating elsewhere in the passage does not.
    const nearName = new RegExp(
      `${layerName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\s+(${VERSION_RE_SOURCE})`,
      'i',
    ).exec(input.text);
    const version = nearName?.[1]?.trim() ?? (mentionedVersions.length === 1 ? mentionedVersions[0]! : null);

    const reasons: string[] = [];
    if (candidate.namedOutright) reasons.push(`names "${layerName}" directly`);
    if (candidate.name.matched.length > 0 && !candidate.namedOutright) {
      reasons.push(`uses ${candidate.name.matched.length} of the layer's name words`);
    }
    if (candidate.subject.matched.length > 0) {
      reasons.push(
        `matches its subject vocabulary (${candidate.subject.matched.slice(0, 5).join(', ')})`,
      );
    }
    if (version) reasons.push(`mentions version ${version}`);

    proposals.push({
      layerId: candidate.entry.layer.id,
      layerName,
      version,
      linkType: linkTypeFor(input.segmentType),
      confidence,
      rationale: reasons.length > 0
        ? `This passage ${reasons.join('; ')}.`
        : 'Weak subject overlap only.',
    });
  }

  return proposals;
}

/**
 * What a link to a layer means, given what kind of passage it is.
 *
 * A returned report is a candidate artifact; an assignment is an input to one;
 * everything else is context. Getting this wrong would let a chat message be
 * promoted as though it were an audited deliverable.
 */
function linkTypeFor(segmentType: string | undefined): LinkType {
  switch (segmentType) {
    case 'RETURNED_RESEARCH':
      return 'COMPLETED_ARTIFACT';
    case 'RESEARCH_ASSIGNMENT':
      return 'RESEARCH_INPUT';
    default:
      return 'REFERENCE';
  }
}

/**
 * Text that tries to give instructions to whatever is reading it.
 *
 * Detected so it can be flagged and quarantined from anything that later becomes
 * a prompt — not because this module would obey it (it matches patterns, it does
 * not execute), but because a passage engineered to steer a model should be
 * visible to the person reviewing the import.
 */
const INJECTION_PATTERNS: RegExp[] = [
  /\bignore (?:all |any )?(?:previous|prior|above) instructions\b/i,
  /\bdisregard (?:the )?(?:previous|prior|above|system)\b/i,
  /\byou are now\b/i,
  /\bsystem prompt\b/i,
  /\bnew instructions?\s*:/i,
  /\bact as (?:if you are )?(?:an? )?(?:admin|root|developer mode)\b/i,
  /\b(?:reveal|print|output) (?:your )?(?:system prompt|instructions)\b/i,
];

export function detectInjection(text: string): string[] {
  const found: string[] = [];
  for (const pattern of INJECTION_PATTERNS) {
    const match = pattern.exec(text);
    if (match) found.push(match[0].trim().slice(0, 80));
  }
  return found;
}
