/**
 * The default provider: a complete, deterministic, offline implementation.
 *
 * It exists so the whole pipeline — compile a prompt, "run" it, audit the
 * result, redo, synthesise, freeze — can be exercised end to end with zero
 * credentials and zero network. Everything it returns is clearly labelled as a
 * placeholder: the mock never pretends to have done research, and it never
 * claims anything about project state (it cannot see the database).
 */
import { createHash } from 'node:crypto';
import type {
  AIProvider,
  AuditRequest,
  AuditResponse,
  ChatRequest,
  ChatResponse,
  ProviderStatus,
  ResearchRequest,
  ResearchResponse,
} from './types.ts';

export const MOCK_MODEL = 'mock-deterministic-1';

/** Minimum body length below which a document is reported as too thin to pass. */
const THIN_DOCUMENT_CHARS = 400;

const PLACEHOLDER_MARKER = 'PLACEHOLDER REPORT';

/** Stable id for a request: the same input always yields the same response id. */
function fingerprint(...parts: (string | null | undefined)[]): string {
  return createHash('sha256').update(parts.map((part) => part ?? '').join('\u0000')).digest('hex');
}

/** The canonical name the compiled prompt demands, read back out of the prompt. */
function expectedTitleFromPrompt(prompt: string): string | null {
  const match = /Report title\s*\/\s*canonical name\s*:\s*(.+)/i.exec(prompt);
  const title = match?.[1]?.trim();
  return title && title.length > 0 ? title : null;
}

function bulletList(items: string[], empty: string): string {
  if (items.length === 0) return `- ${empty}`;
  return items.map((item) => `- ${item}`).join('\n');
}

function lastUserMessage(request: ChatRequest): string {
  for (let index = request.messages.length - 1; index >= 0; index -= 1) {
    const message = request.messages[index];
    if (message && message.role === 'user') return message.content;
  }
  return '';
}

interface MockAuditAssessment {
  verdict: string;
  summary: string;
  failures: string[];
  requiredResearchRuns: string[];
  requiredPatches: string[];
  synthesisRequired: boolean;
  freezeEligible: boolean;
  nextAction: string;
}

/**
 * The mock's audit is not a rubber stamp: it applies the checks it can actually
 * perform offline — is there a document at all, is it more than a stub, and does
 * its title match the canonical name the prompt assigned.
 */
function assess(request: AuditRequest): MockAuditAssessment {
  const document = (request.documentText ?? '').trim();
  const expectedTitle = expectedTitleFromPrompt(request.prompt);

  if (document.length === 0) {
    return {
      verdict: 'MORE_RESEARCH',
      summary:
        'No document text was supplied to the audit, so nothing could be inspected. ' +
        'The audit cannot pass an artifact it has not seen.',
      failures: ['No document text was supplied with the audit request.'],
      requiredResearchRuns: expectedTitle ? [expectedTitle] : [],
      requiredPatches: [],
      synthesisRequired: false,
      freezeEligible: false,
      nextAction: '',
    };
  }

  if (document.includes(PLACEHOLDER_MARKER)) {
    return {
      verdict: 'MORE_RESEARCH',
      summary:
        'The document under audit is the local placeholder report generated by the mock ' +
        'provider. It contains no research, so it cannot be approved, synthesised or frozen.',
      failures: [
        'The document is a mock placeholder, not a research report.',
        'No findings, evidence or open questions are present to inspect.',
      ],
      requiredResearchRuns: expectedTitle ? [expectedTitle] : [],
      requiredPatches: [],
      synthesisRequired: false,
      freezeEligible: false,
      nextAction: '',
    };
  }

  if (document.length < THIN_DOCUMENT_CHARS) {
    return {
      verdict: 'MORE_RESEARCH',
      summary:
        `The document is ${document.length} characters long, below the ${THIN_DOCUMENT_CHARS}-character ` +
        'floor this audit treats as a usable research artifact.',
      failures: ['The document is too short to contain the required sections.'],
      requiredResearchRuns: expectedTitle ? [expectedTitle] : [],
      requiredPatches: [],
      synthesisRequired: false,
      freezeEligible: false,
      nextAction: '',
    };
  }

  if (expectedTitle && !document.includes(expectedTitle)) {
    return {
      verdict: 'PATCH',
      summary:
        `The document body never states its canonical title "${expectedTitle}". Naming is enforced ` +
        'by the platform, so the title has to be corrected before the document is accepted.',
      failures: [`The canonical title "${expectedTitle}" does not appear in the document.`],
      requiredResearchRuns: [],
      requiredPatches: [`Retitle the document exactly "${expectedTitle}".`],
      synthesisRequired: false,
      freezeEligible: false,
      nextAction: '',
    };
  }

  return {
    verdict: 'PASS',
    summary:
      'The document is present, is long enough to be a real artifact, and carries the exact ' +
      'canonical title the prompt assigned. The offline checks this provider can perform all pass.',
    failures: [],
    requiredResearchRuns: [],
    requiredPatches: [],
    synthesisRequired: false,
    freezeEligible: false,
    nextAction: '',
  };
}

export class MockProvider implements AIProvider {
  readonly name = 'mock';

  /**
   * Always available. This is the reason the MVP can ship before any API key
   * exists, so it never reports a degraded status.
   */
  getStatus(): ProviderStatus {
    return {
      name: this.name,
      available: true,
      reason:
        'Deterministic local provider. No API key, no network and no external service are used; ' +
        'the same input always produces the same output.',
      model: MOCK_MODEL,
      capabilities: { chat: true, research: true, audit: true },
    };
  }

  /**
   * Echoes what it was given and says plainly that it knows nothing about the
   * project — state answers must come from the chat's own database tools.
   */
  async chat(request: ChatRequest): Promise<ChatResponse> {
    const last = lastUserMessage(request).trim();
    const text = [
      '[MOCK PROVIDER] No language model was called. This reply is generated locally.',
      '',
      `Messages received : ${request.messages.length}`,
      `System prompt     : ${request.system ? `${request.system.trim().length} characters` : 'none'}`,
      `Last user message : ${last.length > 0 ? JSON.stringify(last.slice(0, 400)) : 'none'}`,
      '',
      'This provider has no access to the project database or the filesystem, so it cannot ' +
        'answer any question about layers, documents, runs or versions. Ask the platform ' +
        'instead — the chat answers those from live queries, not from a model.',
    ].join('\n');
    return {
      text,
      externalResponseId: `mock_chat_${fingerprint(request.system, ...request.messages.map((m) => `${m.role}:${m.content}`)).slice(0, 16)}`,
    };
  }

  /**
   * A placeholder report that is correct in every respect except its content:
   * it carries the exact expected title and filename, so naming can be verified
   * end to end (compile → run → import → canonical-name check) offline.
   */
  async runResearch(request: ResearchRequest): Promise<ResearchResponse> {
    const id = fingerprint(request.prompt, request.expectedConversationTitle).slice(0, 16);
    const promptLines = request.prompt.split('\n').length;
    const text = [
      `# ${request.expectedConversationTitle}`,
      '',
      `> ${PLACEHOLDER_MARKER} — produced locally by the Brain mock provider.`,
      '> No model was called and no research was performed. The naming, structure and',
      '> attachment list below are real; the substance is deliberately absent.',
      '',
      '## 0. Run identity',
      '',
      `Document title     : ${request.expectedConversationTitle}`,
      `Conversation title : ${request.expectedConversationTitle}`,
      `Output filename    : ${request.expectedFilename}`,
      `Model              : ${request.model?.trim() || MOCK_MODEL}`,
      `Prompt fingerprint : ${id}`,
      `Prompt size        : ${request.prompt.length} characters across ${promptLines} lines`,
      '',
      '## 1. Source packet supplied to this run',
      '',
      bulletList(request.requiredAttachments, 'No source documents were required for this run.'),
      '',
      '## 2. Findings',
      '',
      'None. This document exists to prove the pipeline, not to answer the research question.',
      'Replace it by running the compiled prompt in a real research chat and importing the',
      `resulting report as "${request.expectedFilename}".`,
      '',
      '## 3. Open questions',
      '',
      '- Everything the compiled prompt asked remains open.',
      '',
      '## 4. Final naming check',
      '',
      `[x] The title of this document reads exactly: ${request.expectedConversationTitle}`,
      `[x] The conversation is titled exactly: ${request.expectedConversationTitle}`,
      '[x] No extra words were appended to the title.',
      '',
    ].join('\n');
    return { text, externalResponseId: `mock_research_${id}`, model: request.model?.trim() || MOCK_MODEL };
  }

  /**
   * Returns a fenced JSON object in the exact structured-audit shape, so
   * `parseAuditJson` consumes it without special-casing the mock.
   */
  async audit(request: AuditRequest): Promise<AuditResponse> {
    // The dynamic audit pipeline stamps each prompt with its pass, because the
    // three roles expect three different JSON shapes. Answer the right one.
    const dynamicPass = /^BRAIN AUDIT PASS: (EXTRACTION|PRIMARY|ADVERSARIAL|JUDGE)/m.exec(
      request.prompt,
    )?.[1];
    if (dynamicPass) {
      return {
        text: mockDynamicPass(dynamicPass, request),
        externalResponseId: `mock_${dynamicPass.toLowerCase()}_${fingerprint(request.prompt, null).slice(0, 12)}`,
      };
    }

    const assessment = assess(request);
    const payload = {
      verdict: assessment.verdict,
      summary: assessment.summary,
      failures: assessment.failures,
      missingDocuments: [] as string[],
      requiredResearchRuns: assessment.requiredResearchRuns,
      requiredPatches: assessment.requiredPatches,
      synthesisRequired: assessment.synthesisRequired,
      freezeEligible: assessment.freezeEligible,
      nextVersion: null,
      nextAction: assessment.nextAction,
      confidence: 0.5,
    };
    const text = [
      `[MOCK PROVIDER] Offline structural audit — verdict ${assessment.verdict}.`,
      'Only checks that can be performed without a model were applied: document present,',
      'document long enough to be real, canonical title stated in the body.',
      '',
      '```json',
      JSON.stringify(payload, null, 2),
      '```',
      '',
    ].join('\n');
    return {
      text,
      externalResponseId: `mock_audit_${fingerprint(request.prompt, request.documentText).slice(0, 16)}`,
    };
  }
}

// ---------------------------------------------------------------------------
// Dynamic audit passes
// ---------------------------------------------------------------------------

/**
 * Offline stand-ins for the three audit roles.
 *
 * Without a model there is no architectural judgement to be had, and pretending
 * otherwise would be worse than useless: an audit that always says PASS would
 * quietly advance a layer nobody checked. So the mock judges only what can be
 * checked mechanically — is there readable content, does the packet look
 * complete, are dependencies satisfied — and where it cannot know, it declines
 * to advance rather than approving.
 */
function mockDynamicPass(passKey: string, request: AuditRequest): string {
  const prompt = request.prompt;
  const unreadable = /\[NO READABLE CONTENT\]/.test(prompt);
  const missingDeps = /^  Missing dependencies: (.+)$/m.exec(prompt)?.[1] ?? null;
  const missingVersions = /^  Missing: (.+)$/m.exec(prompt)?.[1] ?? null;
  const hasMissing = Boolean(missingDeps) || (missingVersions !== null && missingVersions !== 'none');
  const isPacket = /^AUDIT MODE: LAYER_PACKET$/m.test(prompt);

  if (passKey === 'EXTRACTION' || passKey === 'PRIMARY') {
    const findings: string[] = [];
    if (unreadable) findings.push('At least one artifact has no readable text, so its content could not be assessed.');
    if (hasMissing) findings.push(`The packet is incomplete: ${missingDeps ?? missingVersions} is absent.`);
    return fence({
      assignment_satisfied: unreadable ? 'PARTIAL' : 'YES',
      requirement_findings: findings,
      structural_findings: [],
      boundary_findings: [],
      consistency_findings: [],
      candidate_gaps: [],
      notes:
        'MOCK PROVIDER: no model is configured, so no architectural judgement was performed. ' +
        'Only mechanical checks (readable content, packet completeness, dependency state) ran.',
    });
  }

  if (passKey === 'ADVERSARIAL') {
    const attacks = [
      {
        attack:
          'No model performed a structural audit, so nothing has actually verified that the ' +
          'architecture is strong enough to build on.',
        assessment: 'VALID',
        reasoning:
          'A verdict produced without reading the work is not evidence. Configure a provider, or ' +
          'record the audit by hand after reviewing it yourself.',
      },
    ];
    return fence({
      attacks,
      strongest_reason_not_to_advance:
        'The audit ran offline against the mock provider, so no architectural judgement exists.',
    });
  }

  // JUDGE — decline to advance, and say plainly why.
  if (hasMissing) {
    const missing = (missingDeps ?? missingVersions ?? 'a required document').split(/,\s*/);
    return fence({
      verdict: 'BLOCKED',
      summary:
        'The packet is incomplete, so no verdict on its quality is possible yet. ' +
        'This audit ran offline against the mock provider.',
      gap_classifications: [],
      required_patches: [],
      other_layer_handoffs: [],
      blocking_dependencies: missing,
      synthesis_ready: false,
      freeze_ready: false,
      confidence: 0.2,
      foundational_gap_count: 0,
      targeted_research_runs_required: 0,
      next_action: `Import ${missing[0]} before auditing this ${isPacket ? 'packet' : 'document'} again.`,
    });
  }

  return fence({
    verdict: 'PATCH',
    summary:
      'No AI provider is configured, so this audit performed mechanical checks only and no ' +
      'architectural judgement. It deliberately does not advance the layer: set ANTHROPIC_API_KEY ' +
      'or OPENAI_API_KEY and BRAIN_PROVIDER, or record an audit by hand after reviewing the work.',
    gap_classifications: [],
    required_patches: ['Re-run this audit with a configured AI provider, or record a human audit.'],
    other_layer_handoffs: [],
    blocking_dependencies: [],
    synthesis_ready: false,
    freeze_ready: false,
    confidence: 0.1,
    foundational_gap_count: 0,
    targeted_research_runs_required: 0,
    next_action: 'Configure an AI provider and re-run the audit, or record a human audit verdict.',
  });
}

function fence(payload: unknown): string {
  return ['```json', JSON.stringify(payload, null, 2), '```'].join('\n');
}
