/**
 * Sudoku: generated by digging, checked by solving.
 *
 * ---------------------------------------------------------------------------
 * The generator knows where it dug. The validator is not told
 * ---------------------------------------------------------------------------
 *
 * Uniqueness is the property a sudoku lives or dies by, and it is the one a
 * generator is most tempted to assert. This one does not: the digger removes a
 * pair of cells, hands the resulting grid to `countSolutions`, and puts them
 * back if the answer is not exactly one. The validator then does the identical
 * thing to the *printed* grid, from scratch, knowing nothing about the order
 * cells were removed in or which solution the generator had in mind.
 *
 * That duplication is the point rather than an inefficiency. If the digger had
 * a bug that left two solutions, the validator would find two solutions, and
 * the instance would be refused — which is exactly what could not happen if
 * the validator read a `unique: true` field the generator wrote.
 *
 * ---------------------------------------------------------------------------
 * The canonical form catches a relabelling and says what it does not catch
 * ---------------------------------------------------------------------------
 *
 * Two sudoku grids that differ only by swapping every 3 for every 7, or by
 * being rotated a quarter turn, are the same puzzle to anybody solving them —
 * and a hash of the printed characters calls them different, which would let
 * one puzzle be sold four times over as four. `canonicalise` therefore
 * minimises over the eight dihedral symmetries and relabels digits by first
 * appearance.
 *
 * It does **not** cover band and stack permutations, which would multiply the
 * search by 1 296 for a gain nobody has measured. That is a stated limitation
 * rather than an oversight: two puzzles related by a band swap will hash
 * differently and be treated as two, so the duplicate rate this reports is a
 * floor rather than a ceiling, and it under-counts in the direction that costs
 * a redundant puzzle rather than the direction that lets one through as new.
 */
import {
  artifactHash,
  bandFor,
  check,
  intParam,
  Rng,
  sha256,
  verdictFrom,
  type PuzzleArtifact,
  type PuzzleCheck,
  type PuzzleFormat,
  type PuzzleSpec,
  type PuzzleVerdict,
} from './engine.ts';
import type { PuzzleDifficulty } from '../../../domain/types.ts';

export const SUDOKU_KEY = 'sudoku';

const N = 9;
const CELLS = N * N;
const BLANK = '.';

type Board = number[];

function peersOf(index: number): number[] {
  const row = Math.floor(index / N);
  const col = index % N;
  const boxRow = Math.floor(row / 3) * 3;
  const boxCol = Math.floor(col / 3) * 3;
  const out = new Set<number>();
  for (let i = 0; i < N; i += 1) {
    out.add(row * N + i);
    out.add(i * N + col);
  }
  for (let r = boxRow; r < boxRow + 3; r += 1) {
    for (let c = boxCol; c < boxCol + 3; c += 1) out.add(r * N + c);
  }
  out.delete(index);
  return [...out];
}

/** Precomputed once: the peer sets never change and recomputing them dominates. */
const PEERS: readonly (readonly number[])[] = Object.freeze(
  Array.from({ length: CELLS }, (_unused, index) => Object.freeze(peersOf(index))),
);

function allows(board: Board, index: number, value: number): boolean {
  for (const peer of PEERS[index] as readonly number[]) {
    if (board[peer] === value) return false;
  }
  return true;
}

/**
 * How many solutions this grid has, stopping at `cap`.
 *
 * Stops at the cap deliberately: the only questions ever asked of it are *is
 * it zero*, *is it one* and *is it more than one*, and a grid with a hundred
 * thousand solutions would otherwise be counted to a hundred thousand. It
 * chooses the most-constrained empty cell first, which is what makes an
 * exhaustive count finish at all on a sparse grid.
 */
export function countSolutions(board: Board, cap = 2): number {
  const work = [...board];
  let found = 0;

  const recurse = (): void => {
    if (found >= cap) return;
    let best = -1;
    let bestOptions: number[] = [];
    for (let index = 0; index < CELLS; index += 1) {
      if (work[index] !== 0) continue;
      const options: number[] = [];
      for (let value = 1; value <= N; value += 1) {
        if (allows(work, index, value)) options.push(value);
      }
      if (options.length === 0) return;
      if (best === -1 || options.length < bestOptions.length) {
        best = index;
        bestOptions = options;
        if (options.length === 1) break;
      }
    }
    if (best === -1) {
      found += 1;
      return;
    }
    for (const value of bestOptions) {
      work[best] = value;
      recurse();
      work[best] = 0;
      if (found >= cap) return;
    }
  };

  recurse();
  return found;
}

/** The one solution, or null where there is not exactly one. */
function soleSolution(board: Board): Board | null {
  const work = [...board];
  let answer: Board | null = null;
  let found = 0;

  const recurse = (): void => {
    if (found >= 2) return;
    let best = -1;
    let bestOptions: number[] = [];
    for (let index = 0; index < CELLS; index += 1) {
      if (work[index] !== 0) continue;
      const options: number[] = [];
      for (let value = 1; value <= N; value += 1) {
        if (allows(work, index, value)) options.push(value);
      }
      if (options.length === 0) return;
      if (best === -1 || options.length < bestOptions.length) {
        best = index;
        bestOptions = options;
        if (options.length === 1) break;
      }
    }
    if (best === -1) {
      found += 1;
      if (found === 1) answer = [...work];
      return;
    }
    for (const value of bestOptions) {
      work[best] = value;
      recurse();
      work[best] = 0;
      if (found >= 2) return;
    }
  };

  recurse();
  return found === 1 ? answer : null;
}

function solvedGrid(rng: Rng): Board {
  const board: Board = new Array<number>(CELLS).fill(0);
  const fill = (index: number): boolean => {
    if (index >= CELLS) return true;
    for (const value of rng.shuffle([1, 2, 3, 4, 5, 6, 7, 8, 9])) {
      if (!allows(board, index, value)) continue;
      board[index] = value;
      if (fill(index + 1)) return true;
      board[index] = 0;
    }
    return false;
  };
  fill(0);
  return board;
}

function toRows(board: Board, blankAs: string): string[] {
  const rows: string[] = [];
  for (let r = 0; r < N; r += 1) {
    let line = '';
    for (let c = 0; c < N; c += 1) {
      const value = board[r * N + c] ?? 0;
      line += value === 0 ? blankAs : String(value);
    }
    rows.push(line);
  }
  return rows;
}

function fromRows(rows: readonly string[]): Board | null {
  if (rows.length !== N) return null;
  const board: Board = new Array<number>(CELLS).fill(0);
  for (let r = 0; r < N; r += 1) {
    const line = rows[r] ?? '';
    if (line.length !== N) return null;
    for (let c = 0; c < N; c += 1) {
      const ch = line[c] ?? '';
      if (ch === BLANK) continue;
      if (ch < '1' || ch > '9') return null;
      board[r * N + c] = Number(ch);
    }
  }
  return board;
}

/* --------------------------------------------------------------------------
 * Generating
 * ------------------------------------------------------------------------ */

/** How many givens each band aims to leave. Aims: the dig stops where it must. */
const TARGET_GIVENS: Readonly<Record<PuzzleDifficulty, number>> = Object.freeze({
  EASY: 42,
  MEDIUM: 34,
  HARD: 28,
  EXPERT: 24,
});

function render(spec: PuzzleSpec): PuzzleArtifact {
  const intended = (spec.parameters['difficulty'] as PuzzleDifficulty | undefined) ?? 'MEDIUM';
  const target = TARGET_GIVENS[intended] ?? TARGET_GIVENS.MEDIUM;
  /*
   * Bounded rather than open, so a caller cannot ask for a two-given sudoku
   * and get a long search that eventually gives up quietly. Seventeen is the
   * proven minimum for a unique classic sudoku; below it no dig can succeed,
   * so asking for it is refused rather than attempted.
   */
  const givens = intParam(spec, 'givens', target, 17, 81);
  const rng = new Rng(`${spec.seed}:sudoku`);
  const full = solvedGrid(rng);
  const puzzle = [...full];

  /*
   * Dug in pairs about the centre, which is what makes a sudoku *look* like
   * one. Each removal is provisional: the pair goes back the moment the grid
   * stops having exactly one solution, and the walk simply moves on. The
   * target is therefore an aim rather than a promise, and the artifact says
   * how many givens it actually has rather than how many were asked for.
   */
  let remaining = CELLS;
  for (const index of rng.shuffle(Array.from({ length: CELLS }, (_unused, i) => i))) {
    if (remaining <= givens) break;
    const mirror = CELLS - 1 - index;
    if (puzzle[index] === 0 && puzzle[mirror] === 0) continue;
    const keptA = puzzle[index] ?? 0;
    const keptB = puzzle[mirror] ?? 0;
    puzzle[index] = 0;
    puzzle[mirror] = 0;
    const removed = (keptA !== 0 ? 1 : 0) + (keptB !== 0 && mirror !== index ? 1 : 0);
    if (countSolutions(puzzle, 2) === 1) {
      remaining -= removed;
    } else {
      puzzle[index] = keptA;
      puzzle[mirror] = keptB;
    }
  }

  const grid = toRows(puzzle, BLANK);
  const solution = toRows(full, BLANK);
  return {
    formatKey: SUDOKU_KEY,
    instructions:
      'Fill every empty cell so that each row, each column and each of the nine three-by-three ' +
      'boxes contains the digits 1 to 9 exactly once. There is exactly one solution.',
    grid,
    prompts: [`${remaining} given${remaining === 1 ? '' : 's'}.`],
    solution,
    /*
     * The answer key is the solution grid. Said explicitly because it is not
     * true of every format — a word search's key is a list of coordinates
     * rather than a second grid — and because the key and the solution being
     * one object here is what makes them impossible to disagree.
     */
    answerKey: solution,
    intendedDifficulty: intended,
  };
}

/* --------------------------------------------------------------------------
 * Canonical form
 * ------------------------------------------------------------------------ */

function transform(board: Board, variant: number): Board {
  const out: Board = new Array<number>(CELLS).fill(0);
  for (let r = 0; r < N; r += 1) {
    for (let c = 0; c < N; c += 1) {
      let rr = r;
      let cc = c;
      if (variant & 1) cc = N - 1 - cc;
      if (variant & 2) rr = N - 1 - rr;
      if (variant & 4) {
        const swap = rr;
        rr = cc;
        cc = swap;
      }
      out[rr * N + cc] = board[r * N + c] ?? 0;
    }
  }
  return out;
}

/**
 * The lexicographically smallest reading of this puzzle over the eight
 * dihedral symmetries, with digits relabelled by first appearance.
 *
 * Band and stack permutations are deliberately excluded — see the header. The
 * consequence is stated rather than hidden: this under-detects, so a reported
 * duplicate is certainly one and a reported non-duplicate might not be.
 */
export function canonicalise(board: Board): string {
  let best: string | null = null;
  for (let variant = 0; variant < 8; variant += 1) {
    const moved = transform(board, variant);
    const map = new Map<number, number>();
    let next = 1;
    let text = '';
    for (const value of moved) {
      if (value === 0) {
        text += BLANK;
        continue;
      }
      let label = map.get(value);
      if (label === undefined) {
        label = next;
        next += 1;
        map.set(value, label);
      }
      text += String(label);
    }
    if (best === null || text < best) best = text;
  }
  return sha256(`sudoku:${best ?? ''}`);
}

/* --------------------------------------------------------------------------
 * Validating
 * ------------------------------------------------------------------------ */

/**
 * How hard this is, measured by solving it the way a person does.
 *
 * Naked singles alone is an EASY puzzle; needing hidden singles is MEDIUM;
 * needing anything beyond them is at least HARD, and how much search is left
 * when the simple techniques stall separates HARD from EXPERT.
 *
 * It is deliberately a measure of *these two techniques and then search*
 * rather than a full solver ladder. A richer ladder would be a better
 * measurement and a much larger claim; what is here can be read in a minute
 * and cannot silently drift, and `limitation` says so on the format.
 */
function measure(board: Board): PuzzleDifficulty {
  const work = [...board];
  let usedHidden = false;

  const candidates = (index: number): number[] => {
    const out: number[] = [];
    for (let value = 1; value <= N; value += 1) {
      if (allows(work, index, value)) out.push(value);
    }
    return out;
  };

  for (;;) {
    let progressed = false;
    for (let index = 0; index < CELLS; index += 1) {
      if (work[index] !== 0) continue;
      const options = candidates(index);
      if (options.length === 1) {
        work[index] = options[0] as number;
        progressed = true;
      }
    }
    if (progressed) continue;

    // Hidden singles: a value only one cell in a unit can take.
    const units: number[][] = [];
    for (let i = 0; i < N; i += 1) {
      units.push(Array.from({ length: N }, (_unused, j) => i * N + j));
      units.push(Array.from({ length: N }, (_unused, j) => j * N + i));
    }
    for (let br = 0; br < 3; br += 1) {
      for (let bc = 0; bc < 3; bc += 1) {
        const unit: number[] = [];
        for (let r = br * 3; r < br * 3 + 3; r += 1) {
          for (let c = bc * 3; c < bc * 3 + 3; c += 1) unit.push(r * N + c);
        }
        units.push(unit);
      }
    }
    for (const unit of units) {
      for (let value = 1; value <= N; value += 1) {
        if (unit.some((index) => work[index] === value)) continue;
        const places = unit.filter((index) => work[index] === 0 && allows(work, index, value));
        if (places.length === 1) {
          work[places[0] as number] = value;
          usedHidden = true;
          progressed = true;
        }
      }
    }
    if (!progressed) break;
  }

  const left = work.filter((one) => one === 0).length;
  if (left === 0) return usedHidden ? 'MEDIUM' : 'EASY';
  /*
   * What is left when both techniques stall. A handful of cells is a puzzle
   * one guess resolves; twenty is a puzzle somebody works at.
   */
  return bandFor(left, [1, 1, 16]);
}

function validate(artifact: PuzzleArtifact): PuzzleVerdict {
  const checks: PuzzleCheck[] = [];
  const board = fromRows(artifact.grid);

  if (!board) {
    checks.push(
      check(
        'grid is a nine-by-nine of digits and blanks',
        false,
        `The grid read ${artifact.grid.length} row(s); a sudoku is nine rows of nine ` +
          'characters, each a digit 1-9 or a full stop.',
      ),
    );
    return verdictFrom(checks, null, artifactHash(artifact));
  }
  checks.push(check('grid is a nine-by-nine of digits and blanks', true, 'Nine rows of nine.'));

  /*
   * The givens are checked against each other before anything is solved.
   * A grid with two 4s in one row has no solutions, and `countSolutions`
   * would say so — but "zero solutions" is a much less useful sentence for
   * somebody looking at it than "the givens contradict each other".
   */
  let consistent = true;
  for (let index = 0; index < CELLS && consistent; index += 1) {
    const value = board[index] ?? 0;
    if (value === 0) continue;
    for (const peer of PEERS[index] as readonly number[]) {
      if (board[peer] === value) consistent = false;
    }
  }
  checks.push(
    check(
      'the givens do not contradict each other',
      consistent,
      consistent
        ? 'No digit repeats in any row, column or box among the given cells.'
        : 'Two given cells that share a row, column or box hold the same digit, so the grid ' +
          'has no solution at all.',
    ),
  );

  const givens = board.filter((one) => one !== 0).length;
  checks.push(
    check(
      'at least seventeen givens',
      givens >= 17,
      `${givens} given cell(s). No classic sudoku with fewer than seventeen has a unique ` +
        'solution, so fewer is a grid that cannot be what it claims.',
    ),
  );

  let measured: PuzzleDifficulty | null = null;
  if (consistent && givens >= 17) {
    const count = countSolutions(board, 2);
    checks.push(
      check(
        'exactly one solution',
        count === 1,
        count === 0
          ? 'The grid has no solution.'
          : count === 1
            ? 'Solved from the printed grid alone, with no second solution found.'
            : 'More than one solution. A solver reaching a different answer from the printed ' +
              'key has not made a mistake, which makes this unsellable.',
      ),
    );

    if (count === 1) {
      const found = soleSolution(board);
      const printed = fromRows(artifact.solution);
      const matches =
        found !== null &&
        printed !== null &&
        printed.every((value, index) => value === (found as Board)[index]);
      checks.push(
        check(
          'the printed solution is that solution',
          matches,
          matches
            ? 'The answer key agrees with the grid solved independently.'
            : 'The printed answer key is not the solution this grid actually has. The key and ' +
              'the grid have come apart, which is the defect a reader discovers and a ' +
              'generator never does.',
        ),
      );
      const keyMatches =
        artifact.answerKey.length === artifact.solution.length &&
        artifact.answerKey.every((row, index) => row === artifact.solution[index]);
      checks.push(
        check(
          'the answer key is the solution',
          keyMatches,
          keyMatches ? 'Identical.' : 'The answer key differs from the stated solution.',
        ),
      );
      if (matches) measured = measure(board);
    }
  }

  return verdictFrom(checks, measured, canonicalise(board));
}

export const SUDOKU: PuzzleFormat = {
  key: SUDOKU_KEY,
  title: 'Sudoku',
  authoring: 'GENERATED',
  requiresHumanEdit: false,
  limitation:
    'Uniqueness and solvability are proved from the printed grid. Difficulty is measured by ' +
    'naked and hidden singles and then by what is left, which is a two-technique ladder ' +
    'rather than a full one — so the band is a reading of this measure rather than of how a ' +
    'person will find it. Duplicate detection covers digit relabelling and the eight dihedral ' +
    'symmetries and not band or stack permutation, so it under-detects.',
  render,
  validate,
  /* More sudoku grids exist than anybody will ever print. */
  catalogCeiling: null,
};
